In [1]:
import pandas as pd
import numpy as np

In [2]:
budd = pd.read_excel('find_my_buddy.csv.xlsx', sheet_name='Buddy Sheet')

In [4]:
budd['Any other comments  ?']

0                                                    NaN
1                                         Go Huskies..!!
2                                                    NaN
3                                 Looking for roommates.
4                                                    NaN
5                                                    NaN
6                                                    NaN
7      Need a room for self, willing to share the fla...
8                                                    NaN
9                                                    NaN
10                                                   NaN
11                                                   NaN
12                                                   NaN
13                                                   NaN
14                                                     I
15                                                   NaN
16                                                   NaN
17                                                   NaN
18                                                   NaN
19                                                   NaN
20                                                   NaN
21     Looking for a roommate who's chilled out but a...
22                                                   NaN
23                                                   NaN
24                                                   NaN
25                                                   NaN
26                                                   NaN
27     Free open minded human being who love animals....
28                                                   NaN
29                                                   NaN
                             ...
493                                                  NaN
494                                                  NaN
495                                                  NaN
496                                                  NaN
497                                                  NaN
498                                                  NaN
499                                                  NaN
500                                                  NaN
501                                                  NaN
502                                                  NaN
503                                                  NaN
504                                                  NaN
505                                                  NaN
506                                                  NaN
507                                                  NaN
508                                                  NaN
509                                                  NaN
510                                                  NaN
511    Gimme a Call if need to discuss with me as a p...
512                                  Should be amicable.
513    I don't speak Hindi. I don't mind what my room...
514                                                  NaN
515                                                  NaN
516                                                  NaN
517                                                  NaN
518                                                  NaN
519                                                  NaN
520                                                  NaN
521                                                  NaN
522                                                  NaN
Name: Any other comments  ?, Length: 523, dtype: object

In [3]:
budd[]

Index(['Full Name', 'Email address', 'Gender', 'Hometown',
       'Currently living in ', 'Your Decision', 'Looking for a room mate?',
       'Course ',
       'Please Enter your Branch (If it was not listed in drop down, else leave blank)',
       'Are you open to other branch room mate?',
       'Areas of Interest (In NEU )', 'University Name (UG)',
       'Work experience (In years)',
       'Approximate distance from University (in miles)',
       'Person per room including you ( select all that applies)',
       'Apartment type', 'Can afford a monthly rent  of (Per person)',
       'Facilities required ', 'Alcohol consumption', 'Smoking',
       'Any special preferences for room mates ?', 'Food preference',
       'Culinary skills ', 'I am looking for a room mate', 'Your Hobbies',
       'Facebook profile link (optional)', 'i20 amount', 'VISA status',
       'Planned VISA interview date', 'VISA consulate - city ',
       'Do you need a Flight mate?', 'If yes, then Flight Date?',
       'Any other comments  ?'],
      dtype='object')

Dropping columns which intuitively dont make a difference right now.
'Email address'
'Your Decision'
'Areas of Interest (In NEU )'
'Facebook profile link (optional)'
'i20 amount'
'VISA status'
'Planned VISA interview date'
'VISA consulate - city '
'Do you need a Flight mate?', 'If yes, then Flight Date?'
'Any other comments  ?'
'Any other comments  ?'

In [4]:
budd_new = budd.drop(labels = [ 'i20 amount', 'VISA status', 'Planned VISA interview date', 'VISA consulate - city ',
       'Do you need a Flight mate?', 'If yes, then Flight Date?',
       'Any other comments  ?', 'Email address', 'Your Decision', 'Areas of Interest (In NEU )', 'Facebook profile link (optional)'], axis = 1)

In [5]:
budd_new

,Full Name,Gender,Hometown,Currently living in,Looking for a room mate?,Course,"Please Enter your Branch (If it was not listed in drop down, else leave blank)",Are you open to other branch room mate?,University Name (UG),Work experience (In years),...,Apartment type,Can afford a monthly rent of (Per person),Facilities required,Alcohol consumption,Smoking,Any special preferences for room mates ?,Food preference,Culinary skills,I am looking for a room mate,Your Hobbies
0,Sachin Haldavanekar,Male,Mumbai,Mumbai,Yes,MS Computer Science,NaN,Yes,Mumbai University,3.50,...,"1BHK, 2 BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
1,Sanket Saurav,Male,Patna,Bangalore,Yes,MS Computer Science,NaN,Yes,VTU,3.50,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Non Smokers/Non Drinkers Preferred. Needs to m...,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,"Gaming, Travelling"
2,Viha Bidre,Female,Davanagere,Bangalore,Yes,MS Computer Science,NaN,Yes,Dr. Ambedkar Institute of Technology.,1.80,...,"1BHK, 2 BHK, 3BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Kitchen, Fridge...",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Photography, travelling, DIY art."
3,Sougata Dafader,Male,Kolkata,Kolkata,Yes,MS Computer Science,NaN,Yes,WBUT,3.50,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Hot Water, Heat",Flexible,Flexible,Has humour ;),Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Badminton, TT, football, egames like dota, Cs"
4,Athul Muralidharan,Male,Chennai,Chennai,No,MS Computer Science,NaN,Yes,SRM University,2.00,...,"Studio, 1BHK, 2 BHK, 3BHK",< $700,"Wifi, Security, Kitchen, Fridge",Flexible,Strictly No,"Take it easy people, you are welcome!",Strictly Veg,Sometimes,Who can cook sometimes,Watching movies & making music
5,Megha Suvarna,Female,Mangalore,Pune,Yes,MS Computer Science,NaN,Yes,NaN,2.80,...,"1BHK, 2 BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,"Friendly and not dominating, who likes to keep...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
6,Vishnu,Male,Nileshwar,Bangalore,Yes,MS Engineering Management,NaN,Yes,Msrit,3.00,...,"Studio, 1BHK, 2 BHK",< $400,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Never tried,Who can cook sometimes,"Reading, Football and music"
7,Srashti Kasliwal,Female,Indore,Mumbai,Yes,MS Computer Science,NaN,Yes,NaN,3.50,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Strictly No,Pure veg female,Strictly Veg,Sometimes,Who can cook sometimes,"Reading Books, watching tv series, traveling, ..."
8,Balakumaran,Male,Bangalore,Chennai,Yes,MS Engineering Management,NaN,Yes,Government college of technology,0.60,...,2 BHK,< $500,"Wifi, Gym, Car Parking, Laundry, Hot Water, Se...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
9,Pranav,Male,Pune,Pune,Yes,MS Engineering Management,NaN,Yes,NaN,2.50,...,"2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Gym",Flexible,Flexible,Non vegeterains,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Badminton
10,Harshil Navin Dhruve,Male,Bangalore,Mumbai,Yes,Others,TSM,Yes,VTU,2.50,...,2 BHK,< $550,"Wifi, Gym, Laundry, Kitchen, pool, Fridge",Flexible,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
11,Shravan kumar reddy,Male,Hyderabad,Hyderabad,Yes,MS Computer Science,NaN,Yes,JNTU,0.80,...,"2 BHK, 3BHK",< $500,"Wifi, Laundry, Hot Water, Security, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"TT, Badminton, Music,Cycling"
12,Tejas Harish,Male,Bangalore,Bangalore,Yes,MS Civil Engineering,NaN,Yes,NaN,0.00,...,2 BHK,< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Guitar, tech, swimming"
13,Rohan Taori,Male,Amravati,Nagpur,Yes,MS Engineering Management,Industrial,Yes,Shri Ramdeobaba College of Engineering and Man...,0.00,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Painting and philately
14,Z,Female,D,H,Yes,MS Computer Science,H,Yes,H,5.00,...,Studio,< $500,Wifi,Flexible,Flexible,H,Strictly Non Veg,Sometimes,No culinary skills required,H
15,Mrunal Ghanwat,Female,Pune,Pune,Yes,MS Computer Science,NaN,Yes,Pu,0.00,...,"Studio, 1BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Hiking, dancing"
16,Varun Sundar Rabindranath,Male,Chennai,Chennai,Yes,MS Computer Science,NaN,Yes,Madras Institute of Technology,3.50,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Laundry, Hot Water",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Gaming (AOE and Counter Strike exclusively)
17,Kaustubh Shivdikar,Male,Mumbai,"Wadala, Mumbai",Yes,MS Electrical and Computer Engineering,NaN,Yes,VJTI,1.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Hot Water, Security, Kitchen, Fridge, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Piano guitar, fiddling with electronics"
18,Pratik Devikar,Male,Nagpur,Nagpur,Yes,MS Computer Science,NaN,Yes,Nagpur University,0.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Kitchen, Fridge...",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Football, Video Games"
19,Saumil Patel,Male,Vadodara,Vadodara,Yes,MS Energy Systems,NaN,Yes,"SVIT, Vasad, Gujarat (GTU",0.30,...,2 BHK,< $550,"Wifi, Gym, Hot Water, Kitchen, Fridge, Heat",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Hiking, Sports"
20,Keerthan Bharadwaj,Male,Bangalore,Bangalore,Yes,MS Engineering Management,NaN,Yes,NaN,0.00,...,"2 BHK, 3BHK",< $450,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Strictly No,"Vegetarians preferred. Non vegetarians okay, a...",Strictly Veg,Sometimes,Who can cook sometimes,NaN
21,Sreejith,Male,Kochi,Kochi,Yes,MS Computer Science,NaN,Yes,Toc H Institute of science and technology,1.80,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Flexible,"Social, chilled out, flexible, a musician or a...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Travelling, half decent musician , gaming- Dot..."
22,Rushaabh Saliya,Male,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,Mumbai University,0.00,...,"Studio, 1BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Gaming , reading books , music , chess"
23,Srinidhi Shankar,Male,Bangalore,Bangalore,Yes,MS Computer Science,NaN,Yes,"PESIT SOUTH CAMPUS, VTU",2.00,...,"Studio, 2 BHK, 3BHK",< $500,"Wifi, Hot Water, Kitchen",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,Playing cricket
24,Harsh Sheth,Male,Mumbai,Mumbai,Yes,MS Engineering Management,NaN,Yes,NaN,0.40,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
25,Nipun Midha,Male,Sirsa,Pune,Yes,MS Computer Science,NaN,Yes,MDU,2.20,...,"1BHK, 2 BHK, 3BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
26,Varad,Male,Pune,Pune,Yes,MS Computer Science,NaN,Yes,NaN,0.00,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Strictly No,"Has humour, keeps room tidy, let others sleep ...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Travelling, Listening Music, Watching Movies"
27,Chaitanya Joshi,Male,Mumbai,Mumbai,Yes,MS Engineering Management,NaN,Yes,NaN,0.30,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge",Flexible,Flexible,"Not conservative, Open minded towards everything.",Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,"Photography, guitarist."
28,Cyril Mathew,Male,Pune,Pune,Yes,MS Information Assurance and Cyber Security,NaN,Yes,Vit pune,0.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN
29,VYOM RAJ,Male,LUCKNOW,Raipur,Yes,MS Computer Science,NaN,No,National Institute of Technology Raipur,0.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,Mihir Raichura,Male,Nagpur,Nagpur,Yes,MS Engineering Management,NaN,Yes,SRCOEM Nagpur,1.00,...,2 BHK,< $500,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Basketball , cricket"
494,Manva Pradhan,Female,VADODARA,VADODARA,Yes,MS Computer Science,NaN,Yes,Gujarat Technological University,0.00,...,"1BHK, 2 BHK, 3BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly NO,Strictly No,No demands. Friendly. Understanding. Respects ...,Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,"Dancing, reading and writing"
495,Nikunj Kotecha,Male,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,0.00,...,"2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Kitchen, Fridge, Heat",Flexible,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
496,Akash Tripathi,Male,UP,Mumbai,Yes,MS Industrial Engineering,NaN,Yes,Mumbai University,0.40,...,"2 BHK, 3BHK, 4 BHK",< $1000,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,Football
497,Akshat Karambe,Male,Mumbai,Mumbai,Yes,MS Engineering Management,NaN,Yes,NaN,1.00,...,"1BHK, 2 BHK",< $500,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Strictly No,Non-vegetarian,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Reading, music, sports."
498,Shyama Sastha Krishnamoorthy Srinivasan,Male,Chennai,Bangalore,Yes,MS Computer Systems Engineering,NaN,Yes,SASTRA,1.08,...,"Studio, 1BHK, 2 BHK",< $500,"Wifi, Hot Water, Heat",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,"Books, games, football"
499,Ashutosh Ghildiyal,Male,Dehradun,Dehradun,Yes,MS Computer Science,NaN,Yes,"G.B.P.U.A.T, Pantnagar",1.00,...,1BHK,< $500,"Laundry, Hot Water, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Dota fan
500,Ayush Shukla,Male,Indore,Indore,Yes,MS Computer Science,NaN,Yes,NaN,0.00,...,"1BHK, 2 BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
501,KANDARP VYAS,Male,VADODARA,VADODARA,Yes,MS Information Systems,NaN,Yes,GUJARAT UNIVERSITY,6.00,...,2 BHK,< $500,"Wifi, Hot Water, Kitchen, Fridge, Heat",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
502,Sai Praneeth Macherla,Male,Hyderabad,Hyderabad,Yes,MS Industrial Engineering,NaN,Yes,NaN,0.30,...,"2 BHK, 3BHK",< $500,"Wifi, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Good bathroom manners. Keep things neat.,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Reading books, watching football/soccer, explo..."
503,Dhruv Sharma,Male,Himachal Pradesh,Delhi,Yes,MS Computer Science,NaN,Yes,IP University,1.00,...,"2 BHK, 3BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Flexible,No,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Jogging and movies
504,Patel Parth B.,Male,Mehsana,Surat,Yes,MS Mechanical Engineering,NaN,Yes,Gujarat Technological University,0.00,...,2 BHK,< $550,"Kitchen, Fridge",Flexible,Flexible,vegetarians,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
505,Nishita Sikka,Female,Jalandhar,Jalandhar,Yes,Others,Telecommunication and systems management,Yes,Daviet,0.00,...,"Studio, 2 BHK, 3BHK",< $400,"Wifi, Gym, Car Parking, Laundry, Hot Water, Se...",Flexible,Strictly No,Non veg,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Gyming studying music exploring
506,Shiv Desai,Male,Surat,Surat,Yes,MS Energy Systems,NaN,Yes,NaN,0.00,...,"1BHK, 2 BHK",< $550,"Wifi, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
507,Dhruv Patel,Male,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,0.00,...,2 BHK,< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
508,Siddhika Alve,Female,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,3.00,...,"1BHK, 2 BHK",< $500,"Wifi, Gym, Laundry, Hot Water, Kitchen, Fridge...",Flexible,Flexible,No,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
509,Mayank,Male,Indore,Navi Mumbai,Yes,MS Information Systems,NaN,Yes,RGPV Bhopal,3.00,...,2 BHK,< $550,Wifi,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
510,Ajit Manuel,Male,Chennai,Boston,Yes,MS Engineering Management,NaN,Yes,NaN,4.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Hopefully you don't snore :p,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN
511,Abishek Sampath,Male,Hosur,Hosur,Yes,MS Computer Science,NaN,Yes,Anna University,2.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Ok With Anyone,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,"Books, Gaming, Trekking/Backpacking, TV Shows,..."
512,Vikram Aditya,Male,Hyderabad,Hyderabad,Yes,MS Computer Systems Engineering,NaN,Yes,NaN,0.00,...,"Studio, 1BHK, 2 BHK",< $450,"Wifi, Hot Water, Security, Kitchen, Fridge",Strictly NO,Strictly No,"Should give importance to cleanliness, and res...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Cricket, Badminton, Gym"
513,Saran Prasad Ambikapathy,Male,Chennai,Chennai,Yes,MS Computer Science,NaN,No,Anna University. JCE,5.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Wifi,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Sit, Jump, Dance, Sleep"
514,Parmeet Singh Saluja,Male,Indore,Indore,Yes,MS Computer Science,NaN,Yes,NaN,0.00,...,"1BHK, 2 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Heat",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
515,Raghavan Renganathan,Male,Thanjavur,Thanjavur,Yes,MS Computer Systems Engineering,NaN,Yes,NaN,1.00,...,"1BHK, 2 BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Strictly NO,Strictly No,Pure veg,Strictly Veg,Sometimes,Who can cook sometimes,"Video games, drawing, watching videos, program..."
516,Ananth Kumar Shetty,Male,Mangalore,India,Yes,MS Energy Systems,NaN,Yes,NaN,0.00,...,"1BHK, 2 BHK, 3BHK",< $700,"Wifi, Laundry, Hot Water, Kitchen, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Never tried,Who can cook sometimes,NaN
517,Ankur Bambharoliya,Male,Rajkot,Mumbai,Yes,MS Computer Science,NaN,Yes,Dharmsinh Desai university,3.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,Cricket reading politics programming
518,Sanket Mathur,Male,Jaipur,Jaipur,Yes,MS Computer Science,NaN,No,Jaipur Engineering College and Research Center,3.00,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Kitchen, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
519,Rohit Naik,Male,Navi Mumbai,Navi Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,4.00,...,"2 BHK, 3BHK",< $500,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly Yes,Strictly No,From Mumbai will be preferred,Strictly Non Veg,Sometimes,Who can cook sometimes,NaN
520,Deepak Chandwani,Male,Raipur,Raipur,Yes,MS Information Systems,NaN,Yes,NaN,2.00,...,"1BHK, 2 BHK",< $500,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
521,Nivedita,Female,Indore,Indore,Yes,MS Engineering Management,NaN,Yes,NaN,0.00,...,"Studio, 1BHK, 2 BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
522,Amandeep,Male,Delhi,Delhi,Yes,MS Computer Science,NaN,Yes,IP,2.00,...,"2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN

In [6]:
names = budd_new['Full Name']

In [7]:
budd_new = budd_new.drop(labels = ['Full Name'], axis = 1)

In [8]:
budd_new

,Gender,Hometown,Currently living in,Looking for a room mate?,Course,"Please Enter your Branch (If it was not listed in drop down, else leave blank)",Are you open to other branch room mate?,University Name (UG),Work experience (In years),Approximate distance from University (in miles),...,Apartment type,Can afford a monthly rent of (Per person),Facilities required,Alcohol consumption,Smoking,Any special preferences for room mates ?,Food preference,Culinary skills,I am looking for a room mate,Your Hobbies
0,Male,Mumbai,Mumbai,Yes,MS Computer Science,NaN,Yes,Mumbai University,3.50,<3,...,"1BHK, 2 BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
1,Male,Patna,Bangalore,Yes,MS Computer Science,NaN,Yes,VTU,3.50,<3,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Non Smokers/Non Drinkers Preferred. Needs to m...,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,"Gaming, Travelling"
2,Female,Davanagere,Bangalore,Yes,MS Computer Science,NaN,Yes,Dr. Ambedkar Institute of Technology.,1.80,<3,...,"1BHK, 2 BHK, 3BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Kitchen, Fridge...",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Photography, travelling, DIY art."
3,Male,Kolkata,Kolkata,Yes,MS Computer Science,NaN,Yes,WBUT,3.50,<5,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Hot Water, Heat",Flexible,Flexible,Has humour ;),Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Badminton, TT, football, egames like dota, Cs"
4,Male,Chennai,Chennai,No,MS Computer Science,NaN,Yes,SRM University,2.00,<10,...,"Studio, 1BHK, 2 BHK, 3BHK",< $700,"Wifi, Security, Kitchen, Fridge",Flexible,Strictly No,"Take it easy people, you are welcome!",Strictly Veg,Sometimes,Who can cook sometimes,Watching movies & making music
5,Female,Mangalore,Pune,Yes,MS Computer Science,NaN,Yes,NaN,2.80,<3,...,"1BHK, 2 BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,"Friendly and not dominating, who likes to keep...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
6,Male,Nileshwar,Bangalore,Yes,MS Engineering Management,NaN,Yes,Msrit,3.00,<10,...,"Studio, 1BHK, 2 BHK",< $400,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Never tried,Who can cook sometimes,"Reading, Football and music"
7,Female,Indore,Mumbai,Yes,MS Computer Science,NaN,Yes,NaN,3.50,<5,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Strictly No,Pure veg female,Strictly Veg,Sometimes,Who can cook sometimes,"Reading Books, watching tv series, traveling, ..."
8,Male,Bangalore,Chennai,Yes,MS Engineering Management,NaN,Yes,Government college of technology,0.60,<3,...,2 BHK,< $500,"Wifi, Gym, Car Parking, Laundry, Hot Water, Se...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
9,Male,Pune,Pune,Yes,MS Engineering Management,NaN,Yes,NaN,2.50,<3,...,"2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Gym",Flexible,Flexible,Non vegeterains,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Badminton
10,Male,Bangalore,Mumbai,Yes,Others,TSM,Yes,VTU,2.50,<1,...,2 BHK,< $550,"Wifi, Gym, Laundry, Kitchen, pool, Fridge",Flexible,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
11,Male,Hyderabad,Hyderabad,Yes,MS Computer Science,NaN,Yes,JNTU,0.80,<10,...,"2 BHK, 3BHK",< $500,"Wifi, Laundry, Hot Water, Security, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"TT, Badminton, Music,Cycling"
12,Male,Bangalore,Bangalore,Yes,MS Civil Engineering,NaN,Yes,NaN,0.00,<3,...,2 BHK,< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Guitar, tech, swimming"
13,Male,Amravati,Nagpur,Yes,MS Engineering Management,Industrial,Yes,Shri Ramdeobaba College of Engineering and Man...,0.00,<5,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Painting and philately
14,Female,D,H,Yes,MS Computer Science,H,Yes,H,5.00,<1,...,Studio,< $500,Wifi,Flexible,Flexible,H,Strictly Non Veg,Sometimes,No culinary skills required,H
15,Female,Pune,Pune,Yes,MS Computer Science,NaN,Yes,Pu,0.00,<3,...,"Studio, 1BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Hiking, dancing"
16,Male,Chennai,Chennai,Yes,MS Computer Science,NaN,Yes,Madras Institute of Technology,3.50,<5,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Laundry, Hot Water",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Gaming (AOE and Counter Strike exclusively)
17,Male,Mumbai,"Wadala, Mumbai",Yes,MS Electrical and Computer Engineering,NaN,Yes,VJTI,1.00,<3,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Hot Water, Security, Kitchen, Fridge, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Piano guitar, fiddling with electronics"
18,Male,Nagpur,Nagpur,Yes,MS Computer Science,NaN,Yes,Nagpur University,0.00,<5,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Kitchen, Fridge...",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Football, Video Games"
19,Male,Vadodara,Vadodara,Yes,MS Energy Systems,NaN,Yes,"SVIT, Vasad, Gujarat (GTU",0.30,<3,...,2 BHK,< $550,"Wifi, Gym, Hot Water, Kitchen, Fridge, Heat",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Hiking, Sports"
20,Male,Bangalore,Bangalore,Yes,MS Engineering Management,NaN,Yes,NaN,0.00,<3,...,"2 BHK, 3BHK",< $450,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Strictly No,"Vegetarians preferred. Non vegetarians okay, a...",Strictly Veg,Sometimes,Who can cook sometimes,NaN
21,Male,Kochi,Kochi,Yes,MS Computer Science,NaN,Yes,Toc H Institute of science and technology,1.80,<5,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Flexible,"Social, chilled out, flexible, a musician or a...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Travelling, half decent musician , gaming- Dot..."
22,Male,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,Mumbai University,0.00,<5,...,"Studio, 1BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Gaming , reading books , music , chess"
23,Male,Bangalore,Bangalore,Yes,MS Computer Science,NaN,Yes,"PESIT SOUTH CAMPUS, VTU",2.00,<5,...,"Studio, 2 BHK, 3BHK",< $500,"Wifi, Hot Water, Kitchen",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,Playing cricket
24,Male,Mumbai,Mumbai,Yes,MS Engineering Management,NaN,Yes,NaN,0.40,<3,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
25,Male,Sirsa,Pune,Yes,MS Computer Science,NaN,Yes,MDU,2.20,<5,...,"1BHK, 2 BHK, 3BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
26,Male,Pune,Pune,Yes,MS Computer Science,NaN,Yes,NaN,0.00,<5,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Strictly No,"Has humour, keeps room tidy, let others sleep ...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Travelling, Listening Music, Watching Movies"
27,Male,Mumbai,Mumbai,Yes,MS Engineering Management,NaN,Yes,NaN,0.30,<5,...,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge",Flexible,Flexible,"Not conservative, Open minded towards everything.",Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,"Photography, guitarist."
28,Male,Pune,Pune,Yes,MS Information Assurance and Cyber Security,NaN,Yes,Vit pune,0.00,<5,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN
29,Male,LUCKNOW,Raipur,Yes,MS Computer Science,NaN,No,National Institute of Technology Raipur,0.00,<5,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,Male,Nagpur,Nagpur,Yes,MS Engineering Management,NaN,Yes,SRCOEM Nagpur,1.00,<3,...,2 BHK,< $500,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Basketball , cricket"
494,Female,VADODARA,VADODARA,Yes,MS Computer Science,NaN,Yes,Gujarat Technological University,0.00,<3,...,"1BHK, 2 BHK, 3BHK",< $700,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Strictly NO,Strictly No,No demands. Friendly. Understanding. Respects ...,Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,"Dancing, reading and writing"
495,Male,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,0.00,<5,...,"2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Kitchen, Fridge, Heat",Flexible,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
496,Male,UP,Mumbai,Yes,MS Industrial Engineering,NaN,Yes,Mumbai University,0.40,<3,...,"2 BHK, 3BHK, 4 BHK",< $1000,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,Football
497,Male,Mumbai,Mumbai,Yes,MS Engineering Management,NaN,Yes,NaN,1.00,<3,...,"1BHK, 2 BHK",< $500,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Strictly No,Non-vegetarian,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Reading, music, sports."
498,Male,Chennai,Bangalore,Yes,MS Computer Systems Engineering,NaN,Yes,SASTRA,1.08,<3,...,"Studio, 1BHK, 2 BHK",< $500,"Wifi, Hot Water, Heat",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,"Books, games, football"
499,Male,Dehradun,Dehradun,Yes,MS Computer Science,NaN,Yes,"G.B.P.U.A.T, Pantnagar",1.00,<3,...,1BHK,< $500,"Laundry, Hot Water, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Dota fan
500,Male,Indore,Indore,Yes,MS Computer Science,NaN,Yes,NaN,0.00,<3,...,"1BHK, 2 BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
501,Male,VADODARA,VADODARA,Yes,MS Information Systems,NaN,Yes,GUJARAT UNIVERSITY,6.00,<5,...,2 BHK,< $500,"Wifi, Hot Water, Kitchen, Fridge, Heat",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
502,Male,Hyderabad,Hyderabad,Yes,MS Industrial Engineering,NaN,Yes,NaN,0.30,<3,...,"2 BHK, 3BHK",< $500,"Wifi, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Good bathroom manners. Keep things neat.,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Reading books, watching football/soccer, explo..."
503,Male,Himachal Pradesh,Delhi,Yes,MS Computer Science,NaN,Yes,IP University,1.00,<3,...,"2 BHK, 3BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Flexible,No,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Jogging and movies
504,Male,Mehsana,Surat,Yes,MS Mechanical Engineering,NaN,Yes,Gujarat Technological University,0.00,<3,...,2 BHK,< $550,"Kitchen, Fridge",Flexible,Flexible,vegetarians,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
505,Female,Jalandhar,Jalandhar,Yes,Others,Telecommunication and systems management,Yes,Daviet,0.00,<1,...,"Studio, 2 BHK, 3BHK",< $400,"Wifi, Gym, Car Parking, Laundry, Hot Water, Se...",Flexible,Strictly No,Non veg,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Gyming studying music exploring
506,Male,Surat,Surat,Yes,MS Energy Systems,NaN,Yes,NaN,0.00,<5,...,"1BHK, 2 BHK",< $550,"Wifi, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
507,Male,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,0.00,<1,...,2 BHK,< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
508,Female,Mumbai,Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,3.00,<1,...,"1BHK, 2 BHK",< $500,"Wifi, Gym, Laundry, Hot Water, Kitchen, Fridge...",Flexible,Flexible,No,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
509,Male,Indore,Navi Mumbai,Yes,MS Information Systems,NaN,Yes,RGPV Bhopal,3.00,<3,...,2 BHK,< $550,Wifi,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
510,Male,Chennai,Boston,Yes,MS Engineering Management,NaN,Yes,NaN,4.00,<1,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Hopefully you don't snore :p,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN
511,Male,Hosur,Hosur,Yes,MS Computer Science,NaN,Yes,Anna University,2.00,<10,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,Ok With Anyone,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,"Books, Gaming, Trekking/Backpacking, TV Shows,..."
512,Male,Hyderabad,Hyderabad,Yes,MS Computer Systems Engineering,NaN,Yes,NaN,0.00,<3,...,"Studio, 1BHK, 2 BHK",< $450,"Wifi, Hot Water, Security, Kitchen, Fridge",Strictly NO,Strictly No,"Should give importance to cleanliness, and res...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Cricket, Badminton, Gym"
513,Male,Chennai,Chennai,Yes,MS Computer Science,NaN,No,Anna University. JCE,5.00,<5,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Wifi,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Sit, Jump, Dance, Sleep"
514,Male,Indore,Indore,Yes,MS Computer Science,NaN,Yes,NaN,0.00,<3,...,"1BHK, 2 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Heat",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
515,Male,Thanjavur,Thanjavur,Yes,MS Computer Systems Engineering,NaN,Yes,NaN,1.00,<3,...,"1BHK, 2 BHK",< $500,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Strictly NO,Strictly No,Pure veg,Strictly Veg,Sometimes,Who can cook sometimes,"Video games, drawing, watching videos, program..."
516,Male,Mangalore,India,Yes,MS Energy Systems,NaN,Yes,NaN,0.00,<3,...,"1BHK, 2 BHK, 3BHK",< $700,"Wifi, Laundry, Hot Water, Kitchen, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Never tried,Who can cook sometimes,NaN
517,Male,Rajkot,Mumbai,Yes,MS Computer Science,NaN,Yes,Dharmsinh Desai university,3.00,<3,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Kitchen, Fridge, Heat",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,Cricket reading politics programming
518,Male,Jaipur,Jaipur,Yes,MS Computer Science,NaN,No,Jaipur Engineering College and Research Center,3.00,<1,...,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,"Wifi, Kitchen, Heat",Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
519,Male,Navi Mumbai,Navi Mumbai,Yes,MS Information Systems,NaN,Yes,NaN,4.00,<3,...,"2 BHK, 3BHK",< $500,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly Yes,Strictly No,From Mumbai will be preferred,Strictly Non Veg,Sometimes,Who can cook sometimes,NaN
520,Male,Raipur,Raipur,Yes,MS Information Systems,NaN,Yes,NaN,2.00,<3,...,"1BHK, 2 BHK",< $500,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
521,Female,Indore,Indore,Yes,MS Engineering Management,NaN,Yes,NaN,0.00,<10,...,"Studio, 1BHK, 2 BHK",< $550,"Wifi, Gym, Laundry, Hot Water, Security, Kitch...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
522,Male,Delhi,Delhi,Yes,MS Computer Science,NaN,Yes,IP,2.00,<1,...,"2 BHK, 3BHK, 4 BHK",< $550,"Wifi, Laundry, Hot Water, Security, Kitchen, F...",Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN

## Start categorizing variables

#### Male, Female to 0, 1

In [9]:
budd_new['Gender'].replace(['Male','Female'], [0, 1], inplace = True)

In [10]:
budd_new = budd_new.drop(['Facilities required '], axis = 1)

In [11]:
budd_new.columns

Index(['Gender', 'Hometown', 'Currently living in ',
       'Looking for a room mate?', 'Course ',
       'Please Enter your Branch (If it was not listed in drop down, else leave blank)',
       'Are you open to other branch room mate?', 'University Name (UG)',
       'Work experience (In years)',
       'Approximate distance from University (in miles)',
       'Person per room including you ( select all that applies)',
       'Apartment type', 'Can afford a monthly rent  of (Per person)',
       'Alcohol consumption', 'Smoking',
       'Any special preferences for room mates ?', 'Food preference',
       'Culinary skills ', 'I am looking for a room mate', 'Your Hobbies'],
      dtype='object')

In [12]:
budd_new.columns = ['gender', 'hometown', 'current_city',
       'need_roommate', 'course',
       'edu_prog',
       'open_to_other_branch', 'undergrad_uni',
       'work_ex',
       'dist_from_uni',
       'person_per_room',
       'apt_type', 'rent_budget',
       'alcohol', 'smoking',
       'special_pref', 'food_pref',
       'cul_skills ', 'looking_for_roommate', 'hobbies']

In [13]:
budd_new = budd_new.drop(['edu_prog'], axis = 1)

In [14]:
budd_new.columns

Index(['gender', 'hometown', 'current_city', 'need_roommate', 'course',
       'open_to_other_branch', 'undergrad_uni', 'work_ex', 'dist_from_uni',
       'person_per_room', 'apt_type', 'rent_budget', 'alcohol', 'smoking',
       'special_pref', 'food_pref', 'cul_skills ', 'looking_for_roommate',
       'hobbies'],
      dtype='object')

In [15]:
budd_new.course.unique()

array(['MS Computer Science', 'MS Engineering Management', 'Others',
       'MS Civil Engineering', 'MS Electrical and Computer Engineering',
       'MS Energy Systems', 'MS Information Systems',
       'MS Information Assurance and Cyber Security', 'MS Data Science',
       'MS Mechanical Engineering', 'MS Computer Systems Engineering',
       nan, 'MS Industrial Engineering', 'MS Biotechnology',
       'MS Project Management'], dtype=object)

In [16]:
budd_new

,gender,hometown,current_city,need_roommate,course,open_to_other_branch,undergrad_uni,work_ex,dist_from_uni,person_per_room,apt_type,rent_budget,alcohol,smoking,special_pref,food_pref,cul_skills,looking_for_roommate,hobbies
0,0,Mumbai,Mumbai,Yes,MS Computer Science,Yes,Mumbai University,3.50,<3,"1, 2, 3","1BHK, 2 BHK",< $550,Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
1,0,Patna,Bangalore,Yes,MS Computer Science,Yes,VTU,3.50,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,Flexible,Non Smokers/Non Drinkers Preferred. Needs to m...,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,"Gaming, Travelling"
2,1,Davanagere,Bangalore,Yes,MS Computer Science,Yes,Dr. Ambedkar Institute of Technology.,1.80,<3,2,"1BHK, 2 BHK, 3BHK",< $550,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Photography, travelling, DIY art."
3,0,Kolkata,Kolkata,Yes,MS Computer Science,Yes,WBUT,3.50,<5,"2, 3, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,Has humour ;),Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Badminton, TT, football, egames like dota, Cs"
4,0,Chennai,Chennai,No,MS Computer Science,Yes,SRM University,2.00,<10,"2, 3","Studio, 1BHK, 2 BHK, 3BHK",< $700,Flexible,Strictly No,"Take it easy people, you are welcome!",Strictly Veg,Sometimes,Who can cook sometimes,Watching movies & making music
5,1,Mangalore,Pune,Yes,MS Computer Science,Yes,NaN,2.80,<3,1,"1BHK, 2 BHK",< $550,Flexible,Flexible,"Friendly and not dominating, who likes to keep...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
6,0,Nileshwar,Bangalore,Yes,MS Engineering Management,Yes,Msrit,3.00,<10,"1, 2","Studio, 1BHK, 2 BHK",< $400,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Never tried,Who can cook sometimes,"Reading, Football and music"
7,1,Indore,Mumbai,Yes,MS Computer Science,Yes,NaN,3.50,<5,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,Flexible,Strictly No,Pure veg female,Strictly Veg,Sometimes,Who can cook sometimes,"Reading Books, watching tv series, traveling, ..."
8,0,Bangalore,Chennai,Yes,MS Engineering Management,Yes,Government college of technology,0.60,<3,"4, I can stay in Hall too",2 BHK,< $500,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
9,0,Pune,Pune,Yes,MS Engineering Management,Yes,NaN,2.50,<3,"3, 4","2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,Non vegeterains,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Badminton
10,0,Bangalore,Mumbai,Yes,Others,Yes,VTU,2.50,<1,2,2 BHK,< $550,Flexible,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
11,0,Hyderabad,Hyderabad,Yes,MS Computer Science,Yes,JNTU,0.80,<10,"1, 2, 3","2 BHK, 3BHK",< $500,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"TT, Badminton, Music,Cycling"
12,0,Bangalore,Bangalore,Yes,MS Civil Engineering,Yes,NaN,0.00,<3,1,2 BHK,< $550,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Guitar, tech, swimming"
13,0,Amravati,Nagpur,Yes,MS Engineering Management,Yes,Shri Ramdeobaba College of Engineering and Man...,0.00,<5,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Painting and philately
14,1,D,H,Yes,MS Computer Science,Yes,H,5.00,<1,2,Studio,< $500,Flexible,Flexible,H,Strictly Non Veg,Sometimes,No culinary skills required,H
15,1,Pune,Pune,Yes,MS Computer Science,Yes,Pu,0.00,<3,2,"Studio, 1BHK",< $550,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Hiking, dancing"
16,0,Chennai,Chennai,Yes,MS Computer Science,Yes,Madras Institute of Technology,3.50,<5,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Gaming (AOE and Counter Strike exclusively)
17,0,Mumbai,"Wadala, Mumbai",Yes,MS Electrical and Computer Engineering,Yes,VJTI,1.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Piano guitar, fiddling with electronics"
18,0,Nagpur,Nagpur,Yes,MS Computer Science,Yes,Nagpur University,0.00,<5,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Football, Video Games"
19,0,Vadodara,Vadodara,Yes,MS Energy Systems,Yes,"SVIT, Vasad, Gujarat (GTU",0.30,<3,"2, 4",2 BHK,< $550,Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Hiking, Sports"
20,0,Bangalore,Bangalore,Yes,MS Engineering Management,Yes,NaN,0.00,<3,2,"2 BHK, 3BHK",< $450,Flexible,Strictly No,"Vegetarians preferred. Non vegetarians okay, a...",Strictly Veg,Sometimes,Who can cook sometimes,NaN
21,0,Kochi,Kochi,Yes,MS Computer Science,Yes,Toc H Institute of science and technology,1.80,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,Flexible,"Social, chilled out, flexible, a musician or a...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Travelling, half decent musician , gaming- Dot..."
22,0,Mumbai,Mumbai,Yes,MS Information Systems,Yes,Mumbai University,0.00,<5,"1, 2","Studio, 1BHK",< $500,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,"Gaming , reading books , music , chess"
23,0,Bangalore,Bangalore,Yes,MS Computer Science,Yes,"PESIT SOUTH CAMPUS, VTU",2.00,<5,"3, 4","Studio, 2 BHK, 3BHK",< $500,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,Playing cricket
24,0,Mumbai,Mumbai,Yes,MS Engineering Management,Yes,NaN,0.40,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
25,0,Sirsa,Pune,Yes,MS Computer Science,Yes,MDU,2.20,<5,2,"1BHK, 2 BHK, 3BHK",< $550,Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
26,0,Pune,Pune,Yes,MS Computer Science,Yes,NaN,0.00,<5,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,Strictly No,"Has humour, keeps room tidy, let others sleep ...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Travelling, Listening Music, Watching Movies"
27,0,Mumbai,Mumbai,Yes,MS Engineering Management,Yes,NaN,0.30,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,"Not conservative, Open minded towards everything.",Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,"Photography, guitarist."
28,0,Pune,Pune,Yes,MS Information Assurance and Cyber Security,Yes,Vit pune,0.00,<5,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Strictly Yes,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN
29,0,LUCKNOW,Raipur,Yes,MS Computer Science,No,National Institute of Technology Raipur,0.00,<5,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,0,Nagpur,Nagpur,Yes,MS Engineering Management,Yes,SRCOEM Nagpur,1.00,<3,"1, 2",2 BHK,< $500,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Basketball , cricket"
494,1,VADODARA,VADODARA,Yes,MS Computer Science,Yes,Gujarat Technological University,0.00,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK",< $700,Strictly NO,Strictly No,No demands. Friendly. Understanding. Respects ...,Flexible (I prefer veg or Non -veg for myself...,Expert,No culinary skills required,"Dancing, reading and writing"
495,0,Mumbai,Mumbai,Yes,MS Information Systems,Yes,NaN,0.00,<5,1,"2 BHK, 3BHK, 4 BHK",< $550,Flexible,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
496,0,UP,Mumbai,Yes,MS Industrial Engineering,Yes,Mumbai University,0.40,<3,1,"2 BHK, 3BHK, 4 BHK",< $1000,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,Football
497,0,Mumbai,Mumbai,Yes,MS Engineering Management,Yes,NaN,1.00,<3,"3, 4","1BHK, 2 BHK",< $500,Flexible,Strictly No,Non-vegetarian,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Reading, music, sports."
498,0,Chennai,Bangalore,Yes,MS Computer Systems Engineering,Yes,SASTRA,1.08,<3,"1, 2","Studio, 1BHK, 2 BHK",< $500,Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,"Books, games, football"
499,0,Dehradun,Dehradun,Yes,MS Computer Science,Yes,"G.B.P.U.A.T, Pantnagar",1.00,<3,1,1BHK,< $500,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,Dota fan
500,0,Indore,Indore,Yes,MS Computer Science,Yes,NaN,0.00,<3,2,"1BHK, 2 BHK",< $550,Strictly NO,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
501,0,VADODARA,VADODARA,Yes,MS Information Systems,Yes,GUJARAT UNIVERSITY,6.00,<5,4,2 BHK,< $500,Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
502,0,Hyderabad,Hyderabad,Yes,MS Industrial Engineering,Yes,NaN,0.30,<3,2,"2 BHK, 3BHK",< $500,Flexible,Flexible,Good bathroom manners. Keep things neat.,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Reading books, watching football/soccer, explo..."
503,0,Himachal Pradesh,Delhi,Yes,MS Computer Science,Yes,IP University,1.00,<3,"1, 2","2 BHK, 3BHK",< $550,Flexible,Flexible,No,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Jogging and movies
504,0,Mehsana,Surat,Yes,MS Mechanical Engineering,Yes,Gujarat Technological University,0.00,<3,"1, 2, 3, 4, I can stay in Hall too",2 BHK,< $550,Flexible,Flexible,vegetarians,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
505,1,Jalandhar,Jalandhar,Yes,Others,Yes,Daviet,0.00,<1,3,"Studio, 2 BHK, 3BHK",< $400,Flexible,Strictly No,Non veg,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,Gyming studying music exploring
506,0,Surat,Surat,Yes,MS Energy Systems,Yes,NaN,0.00,<5,2,"1BHK, 2 BHK",< $550,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
507,0,Mumbai,Mumbai,Yes,MS Information Systems,Yes,NaN,0.00,<1,"2, I can stay in Hall too",2 BHK,< $550,Flexible,Flexible,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
508,1,Mumbai,Mumbai,Yes,MS Information Systems,Yes,NaN,3.00,<1,4,"1BHK, 2 BHK",< $500,Flexible,Flexible,No,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
509,0,Indore,Navi Mumbai,Yes,MS Information Systems,Yes,RGPV Bhopal,3.00,<3,I can stay in Hall too,2 BHK,< $550,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
510,0,Chennai,Boston,Yes,MS Engineering Management,Yes,NaN,4.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,Hopefully you don't snore :p,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN
511,0,Hosur,Hosur,Yes,MS Computer Science,Yes,Anna University,2.00,<10,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,Ok With Anyone,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,"Books, Gaming, Trekking/Backpacking, TV Shows,..."
512,0,Hyderabad,Hyderabad,Yes,MS Computer Systems Engineering,Yes,NaN,0.00,<3,"1, 2","Studio, 1BHK, 2 BHK",< $450,Strictly NO,Strictly No,"Should give importance to cleanliness, and res...",Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Cricket, Badminton, Gym"
513,0,Chennai,Chennai,Yes,MS Computer Science,No,Anna University. JCE,5.00,<5,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,"Sit, Jump, Dance, Sleep"
514,0,Indore,Indore,Yes,MS Computer Science,Yes,NaN,0.00,<3,"1, 2","1BHK, 2 BHK",< $550,Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
515,0,Thanjavur,Thanjavur,Yes,MS Computer Systems Engineering,Yes,NaN,1.00,<3,2,"1BHK, 2 BHK",< $500,Strictly NO,Strictly No,Pure veg,Strictly Veg,Sometimes,Who can cook sometimes,"Video games, drawing, watching videos, program..."
516,0,Mangalore,India,Yes,MS Energy Systems,Yes,NaN,0.00,<3,"2, 3, 4","1BHK, 2 BHK, 3BHK",< $700,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Never tried,Who can cook sometimes,NaN
517,0,Rajkot,Mumbai,Yes,MS Computer Science,Yes,Dharmsinh Desai university,3.00,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Expert,Who can cook sometimes,Cricket reading politics programming
518,0,Jaipur,Jaipur,Yes,MS Computer Science,No,Jaipur Engineering College and Research Center,3.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,Strictly No,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
519,0,Navi Mumbai,Navi Mumbai,Yes,MS Information Systems,Yes,NaN,4.00,<3,"1, 2","2 BHK, 3BHK",< $500,Strictly Yes,Strictly No,From Mumbai will be preferred,Strictly Non Veg,Sometimes,Who can cook sometimes,NaN
520,0,Raipur,Raipur,Yes,MS Information Systems,Yes,NaN,2.00,<3,"2, 3","1BHK, 2 BHK",< $500,Strictly NO,Strictly No,NaN,Strictly Veg,Sometimes,Who can cook sometimes,NaN
521,1,Indore,Indore,Yes,MS Engineering Management,Yes,NaN,0.00,<10,1,"Studio, 1BHK, 2 BHK",< $550,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,Who can cook sometimes,NaN
522,0,Delhi,Delhi,Yes,MS Computer Science,Yes,IP,2.00,<1,"1, 2","2 BHK, 3BHK, 4 BHK",< $550,Flexible,Flexible,NaN,Flexible (I prefer veg or Non -veg for myself...,Sometimes,No culinary skills required,NaN

In [17]:
one_hot_course = pd.get_dummies(budd_new['course'])

In [18]:
budd_new.hometown.unique()

array(['Mumbai', 'Patna', 'Davanagere', 'Kolkata', 'Chennai',
       'Mangalore ', 'Nileshwar', 'Indore', 'Bangalore ', 'Pune',
       'Bangalore', 'Hyderabad', 'Amravati ', 'D', 'Nagpur', 'Vadodara',
       'Kochi', 'Sirsa', 'LUCKNOW', 'Jabalpur', 'Margao Goa',
       'Hyderabad ', 'Gujarat', 'Gurgaon', 'Vijayawada', 'Mulund',
       'Amravati', 'Visakhapatnam', 'Kalaburagi', 'Udupi Karnataka',
       'Delhi', 'tamil nadu', 'Mumbai ', 'Dehradun', 'Azamgarh',
       'Thanjavur ', 'Delhi ', 'Pune ', 'Surat', 'Mysore', 'Gulbarga',
       'Jaipur ', 'Vadodara ', 'Chennai ', 'MEERUT', 'Pondicherry',
       'Chittaurgarh, Rajasthan ', 'lucknow', 'Tamilnadu ', 'Godhra',
       'Thrissur, Kerala, India', 'Jaipur, Rajasthan', 'Navi Mumbai',
       'Orissa', 'chennai', 'uttar pradesh', 'Kolhapur',
       'Mysore/Bangalore', 'Jaipur', 'Jalgaon', 'Aurangabad', 'nellore',
       'Ahmedabad', 'Ahmedabad ', 'Sangli, MH', 'Thane', 'SATARA', 'vapi',
       'Mangalore', 'Mangalore, Karnataka', 'Mumbai, India', 'Patna ',
       'Ahmedabab', 'Bengaluru', 'Bangalore/Mysore', 'Abu Dhabi', 'Nasik',
       'Jabalpur, MP', 'Coimbatore, Tamil Nadu ', 'Nashik', 'Bhopal',
       'Bhilai', 'Rishikesh, Uttarakhand, India', 'Coimbatore ', 'Rajkot',
       'Goa', 'Manglore', 'Satara', 'Raipur', 'Giridih, JH', 'Madikeri',
       'Bangalore, karnataka', 'Kerala', 'Cuttack', 'Faridabad(NCR)',
       'Meerut', 'Lucknow', 'Nellore, Andhra Pradesh', 'Tamil nadu',
       'Bhopal/Nagpur', 'Patras', 'Mangalore,Karnataka', 'India',
       'Miraj ', 'Gulbarga ', 'thane', 'Aurangabad/Pune', 'Amritsar',
       'Noida', 'mumbai', 'COIMBATORE', 'TRICHY', 'Guntur', 'Latur',
       'Thane,Mumbai', 'NAGPUR', 'Kanpur (U.P)', 'Nigdi Pune',
       'New Delhi ', 'Thrissur Kerala', 'New Delhi', 'Manipal',
       'Dombivli', 'Kolkata, India', 'Ajmer', 'Kalyan', 'Ranchi',
       'Navsari', 'MUMBAI', 'Chandigarh', 'sakaleshpur', 'Ghaziabad',
       'Nagpur ', 'Rasayani', 'Morbi', 'Bhilai, Durg', 'Sakaleshpur',
       'Thane(Mumbai)', 'Bangalore, India', 'Trivandrum', 'Kanpur ',
       'Dahod', 'Surendranagar, Gujarat', 'Trichy', 'Solapur',
       'Aurangabad ', 'Indian', 'Odisha', 'Bhubaneswar', 'Boston ',
       'Hubli ', 'chittoor', 'Nellore ', 'hyderabad', 'Mandya',
       'Faridabad', 'Dombivli ', 'Coimbatore', 'Khopoli', 'Coorg',
       'Belgaum', 'sangli ', 'Vaododara', 'Haryana ', 'Palakkad',
       'COIMBATORE ', 'Banglore ', 'zz', 'VADODARA', 'UP',
       'Himachal Pradesh', 'Mehsana', 'Jalandhar', 'Hosur', 'Thanjavur',
       'Rajkot '], dtype=object)

In [19]:
budd_new = budd_new.join(one_hot_course)
budd_new = budd_new.drop('course', axis = 1)

In [20]:
budd_new = budd_new.drop(522)

In [21]:
budd_new

,gender,hometown,current_city,need_roommate,open_to_other_branch,undergrad_uni,work_ex,dist_from_uni,person_per_room,apt_type,...,MS Data Science,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others
0,0,Mumbai,Mumbai,Yes,Yes,Mumbai University,3.50,<3,"1, 2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
1,0,Patna,Bangalore,Yes,Yes,VTU,3.50,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
2,1,Davanagere,Bangalore,Yes,Yes,Dr. Ambedkar Institute of Technology.,1.80,<3,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
3,0,Kolkata,Kolkata,Yes,Yes,WBUT,3.50,<5,"2, 3, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
4,0,Chennai,Chennai,No,Yes,SRM University,2.00,<10,"2, 3","Studio, 1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
5,1,Mangalore,Pune,Yes,Yes,NaN,2.80,<3,1,"1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
6,0,Nileshwar,Bangalore,Yes,Yes,Msrit,3.00,<10,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0
7,1,Indore,Mumbai,Yes,Yes,NaN,3.50,<5,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
8,0,Bangalore,Chennai,Yes,Yes,Government college of technology,0.60,<3,"4, I can stay in Hall too",2 BHK,...,0,0,0,1,0,0,0,0,0,0
9,0,Pune,Pune,Yes,Yes,NaN,2.50,<3,"3, 4","2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
10,0,Bangalore,Mumbai,Yes,Yes,VTU,2.50,<1,2,2 BHK,...,0,0,0,0,0,0,0,0,0,1
11,0,Hyderabad,Hyderabad,Yes,Yes,JNTU,0.80,<10,"1, 2, 3","2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
12,0,Bangalore,Bangalore,Yes,Yes,NaN,0.00,<3,1,2 BHK,...,0,0,0,0,0,0,0,0,0,0
13,0,Amravati,Nagpur,Yes,Yes,Shri Ramdeobaba College of Engineering and Man...,0.00,<5,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
14,1,D,H,Yes,Yes,H,5.00,<1,2,Studio,...,0,0,0,0,0,0,0,0,0,0
15,1,Pune,Pune,Yes,Yes,Pu,0.00,<3,2,"Studio, 1BHK",...,0,0,0,0,0,0,0,0,0,0
16,0,Chennai,Chennai,Yes,Yes,Madras Institute of Technology,3.50,<5,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
17,0,Mumbai,"Wadala, Mumbai",Yes,Yes,VJTI,1.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,1,0,0,0,0,0,0,0,0
18,0,Nagpur,Nagpur,Yes,Yes,Nagpur University,0.00,<5,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
19,0,Vadodara,Vadodara,Yes,Yes,"SVIT, Vasad, Gujarat (GTU",0.30,<3,"2, 4",2 BHK,...,0,0,1,0,0,0,0,0,0,0
20,0,Bangalore,Bangalore,Yes,Yes,NaN,0.00,<3,2,"2 BHK, 3BHK",...,0,0,0,1,0,0,0,0,0,0
21,0,Kochi,Kochi,Yes,Yes,Toc H Institute of science and technology,1.80,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
22,0,Mumbai,Mumbai,Yes,Yes,Mumbai University,0.00,<5,"1, 2","Studio, 1BHK",...,0,0,0,0,0,0,1,0,0,0
23,0,Bangalore,Bangalore,Yes,Yes,"PESIT SOUTH CAMPUS, VTU",2.00,<5,"3, 4","Studio, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
24,0,Mumbai,Mumbai,Yes,Yes,NaN,0.40,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
25,0,Sirsa,Pune,Yes,Yes,MDU,2.20,<5,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
26,0,Pune,Pune,Yes,Yes,NaN,0.00,<5,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
27,0,Mumbai,Mumbai,Yes,Yes,NaN,0.30,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
28,0,Pune,Pune,Yes,Yes,Vit pune,0.00,<5,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,1,0,0,0,0
29,0,LUCKNOW,Raipur,Yes,No,National Institute of Technology Raipur,0.00,<5,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,Pune,Pune,Yes,Yes,NaN,4.00,<3,"3, 4","1BHK, 2 BHK",...,0,0,0,0,0,1,0,0,0,0
493,0,Nagpur,Nagpur,Yes,Yes,SRCOEM Nagpur,1.00,<3,"1, 2",2 BHK,...,0,0,0,1,0,0,0,0,0,0
494,1,VADODARA,VADODARA,Yes,Yes,Gujarat Technological University,0.00,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
495,0,Mumbai,Mumbai,Yes,Yes,NaN,0.00,<5,1,"2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
496,0,UP,Mumbai,Yes,Yes,Mumbai University,0.40,<3,1,"2 BHK, 3BHK, 4 BHK",...,0,0,0,0,1,0,0,0,0,0
497,0,Mumbai,Mumbai,Yes,Yes,NaN,1.00,<3,"3, 4","1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0
498,0,Chennai,Bangalore,Yes,Yes,SASTRA,1.08,<3,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
499,0,Dehradun,Dehradun,Yes,Yes,"G.B.P.U.A.T, Pantnagar",1.00,<3,1,1BHK,...,0,0,0,0,0,0,0,0,0,0
500,0,Indore,Indore,Yes,Yes,NaN,0.00,<3,2,"1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
501,0,VADODARA,VADODARA,Yes,Yes,GUJARAT UNIVERSITY,6.00,<5,4,2 BHK,...,0,0,0,0,0,0,1,0,0,0
502,0,Hyderabad,Hyderabad,Yes,Yes,NaN,0.30,<3,2,"2 BHK, 3BHK",...,0,0,0,0,1,0,0,0,0,0
503,0,Himachal Pradesh,Delhi,Yes,Yes,IP University,1.00,<3,"1, 2","2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
504,0,Mehsana,Surat,Yes,Yes,Gujarat Technological University,0.00,<3,"1, 2, 3, 4, I can stay in Hall too",2 BHK,...,0,0,0,0,0,0,0,1,0,0
505,1,Jalandhar,Jalandhar,Yes,Yes,Daviet,0.00,<1,3,"Studio, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,1
506,0,Surat,Surat,Yes,Yes,NaN,0.00,<5,2,"1BHK, 2 BHK",...,0,0,1,0,0,0,0,0,0,0
507,0,Mumbai,Mumbai,Yes,Yes,NaN,0.00,<1,"2, I can stay in Hall too",2 BHK,...,0,0,0,0,0,0,1,0,0,0
508,1,Mumbai,Mumbai,Yes,Yes,NaN,3.00,<1,4,"1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
509,0,Indore,Navi Mumbai,Yes,Yes,RGPV Bhopal,3.00,<3,I can stay in Hall too,2 BHK,...,0,0,0,0,0,0,1,0,0,0
510,0,Chennai,Boston,Yes,Yes,NaN,4.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
511,0,Hosur,Hosur,Yes,Yes,Anna University,2.00,<10,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
512,0,Hyderabad,Hyderabad,Yes,Yes,NaN,0.00,<3,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
513,0,Chennai,Chennai,Yes,No,Anna University. JCE,5.00,<5,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
514,0,Indore,Indore,Yes,Yes,NaN,0.00,<3,"1, 2","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
515,0,Thanjavur,Thanjavur,Yes,Yes,NaN,1.00,<3,2,"1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
516,0,Mangalore,India,Yes,Yes,NaN,0.00,<3,"2, 3, 4","1BHK, 2 BHK, 3BHK",...,0,0,1,0,0,0,0,0,0,0
517,0,Rajkot,Mumbai,Yes,Yes,Dharmsinh Desai university,3.00,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
518,0,Jaipur,Jaipur,Yes,No,Jaipur Engineering College and Research Center,3.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
519,0,Navi Mumbai,Navi Mumbai,Yes,Yes,NaN,4.00,<3,"1, 2","2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
520,0,Raipur,Raipur,Yes,Yes,NaN,2.00,<3,"2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
521,1,Indore,Indore,Yes,Yes,NaN,0.00,<10,1,"Studio, 1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0

In [22]:
budd_new['hometown'] = budd_new['hometown'].str.strip().str.lower()
budd_new['current_city'] = budd_new['current_city'].str.strip().str.lower()

In [23]:
budd_new['undergrad_uni'] = budd_new['undergrad_uni'].str.strip().str.lower()

In [24]:
np.sum(budd_new['hometown'] == budd_new['current_city'])/len(budd_new)

0.6053639846743295

In [25]:
pd.value_counts(budd_new['undergrad_uni'])

mumbai university                                            55
vtu                                                          19
university of mumbai                                         12
pune university                                              12
university of pune                                            6
vjti                                                          6
anna university                                               5
manipal institute of technology                               4
gujarat technological university                              3
dharmsinh desai university                                    3
indus university                                              3
gtu                                                           3
nagpur university                                             3
sastra university                                             3
kiit university                                               3
mumbai                                                        3
nmims                                                         3
nit trichy                                                    3
msrit                                                         3
bms college of engineering                                    2
pesit                                                         2
vit vellore                                                   2
vit university, vellore                                       2
vellore institute of technology                               2
manav rachna university                                       2
jiit                                                          2
solapur university                                            2
shri ramdeobaba college of engineering and management         2
nirma university                                              2
rgpv                                                          2
                                                             ..
sastra                                                        1
national institute of technology warangal                     1
gujarat university                                            1
chhattisgarh swami vivekanand technical university            1
thadomal shahani engineering college                          1
vishwakarma institute of technology, pune                     1
nmims university                                              1
kumaraguru college of technology, coimbatore                  1
university visveswaraya college of engineering                1
jssate                                                        1
jaypee instituteof information technology, noida              1
dayananda sagar college                                       1
k.j. somaiya college of engineering                           1
vit university                                                1
thadomal shahani engineering college( mumbai university)      1
rns institute of technology                                   1
sies gst, mumbai university                                   1
bit                                                           1
daviet                                                        1
sardar patel institute of technology.( mumbai university)     1
dwarkadas j. sanghvi college of engineering                   1
sit                                                           1
chitkara university                                           1
mu                                                            1
vjti, mumbai                                                  1
mumbai university (sies graduate school of technology)        1
rgpv bhopal                                                   1
rajiv gandhi institute of technology                          1
g.b.p.u.a.t                                                   1
sardar patel college of engineering (spce)                    1
Name: undergrad_uni, Length: 224, dtype: int64

In [26]:
mask = budd_new.undergrad_uni.str.contains('mumbai')

In [27]:
mask

0       True
1      False
2      False
3      False
4      False
5        NaN
6      False
7        NaN
8      False
9        NaN
10     False
11     False
12       NaN
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20       NaN
21     False
22      True
23     False
24       NaN
25     False
26       NaN
27       NaN
28     False
29     False
       ...
492      NaN
493    False
494    False
495      NaN
496     True
497      NaN
498    False
499    False
500      NaN
501    False
502      NaN
503    False
504    False
505    False
506      NaN
507      NaN
508      NaN
509    False
510      NaN
511    False
512      NaN
513    False
514      NaN
515      NaN
516      NaN
517    False
518    False
519      NaN
520      NaN
521      NaN
Name: undergrad_uni, Length: 522, dtype: object

In [30]:
budd_new['undergrad_uni'].loc[mask,:] = 'mumbai university'

ValueError: cannot index with vector containing NA / NaN values

In [61]:
new_unis = np.array(budd_new['undergrad_uni'])

In [62]:
new_unis

array(['mumbai university', 'vtu',
       'dr. ambedkar institute of technology.', 'wbut', 'srm university',
       nan, 'msrit', nan, 'government college of technology', nan, 'vtu',
       'jntu', nan,
       'shri ramdeobaba college of engineering and management', 'h', 'pu',
       'madras institute of technology', 'vjti', 'nagpur university',
       'svit, vasad, gujarat (gtu', nan,
       'toc h institute of science and technology', 'mumbai university',
       'pesit south campus, vtu', nan, 'mdu', nan, nan, 'vit pune',
       'national  institute of technology raipur', nan,
       'biju patnaik university of technology', 'nagpur university',
       'nit trichy', 'vit vellore', 'mumbai university', nan, nan,
       'sri bhagawan mahaveer jain college of engineering',
       'dharmsinh desai university', 'maharishi dayanand university',
       'bits pilani, goa campus', 'jntu', nan, 'mumbai', 'sgbau amravati',
       'mumbai university',
       'indian institute of technology, bhubaneswar (iit bbs)', nan,
       'datta meghe college of engineering, mumbai university',
       'visvesvaraya technological university', 'vtu', nan,
       'ggsipu, delhi', 'uptu', 'university of mumbai', 'sit', 'uptu',
       'vit vellore', 'ceg, anna university',
       'rajalakshmi institute of technology', 'sastra university',
       'pune university', 'pune university',
       'manipal institute of technology', 'nmims', 'bit',
       'university of pune', 'nit surat', 'vtu', 'b.n.m it (vtu)',
       'dwarkadas j. sanghvi college of engineering',
       'vidya vardhaka college of engineering, vtu, mysore',
       'vtu belgaum', 'poornima college of engineering', nan,
       'dharmsinh desai university', nan, nan, nan,
       'jaypee instituteof information technology, noida',
       'pondicherry engineering college',
       'govt college of technology and engineering',
       'rajiv gandhi institute of technology',
       'dhirubhai ambani institute of information and communication technology',
       'mumbai university', nan, 'vtu', nan,
       'amrita school of engineering', nan, 'nirma university',
       'vit university, vellore', nan, nan, 'mits', nan, nan,
       'mumbai university', nan, 'srm university',
       'srm easwari engg collg', 'mpstme', 'sastra university',
       'rns institute of technology', 'vtu', 'ceg, anna university',
       'university visveswaraya college of engineering',
       'mumbai university (fr. conceicao rodrigues institute of technology)',
       'sjce', nan, 'sir padampat singhania university',
       'vellore institute of technology', 'pune university', 'vjti', nan,
       'iit kanpur', 'university of mumbai', 'pune university',
       'gujarat technological university', 'indus university',
       'vjti college', 'mnnit allahabad', nan, 'indus university', 'ddu',
       'pune university', 'jaypee institute of information technology',
       'kjsce', 'vtu (atria institute of technology)', 'jiit',
       'g h raisoni college of engineering nagpur',
       'sies gst, mumbai university', 'dayananda sagar college',
       'mumbai university', 'mumbai university', 'vjti, mumbai',
       'university of mumbai', 'nit allahabad', 'mumbai university',
       'dr. babasaheb ambedkar technological university',
       'kj somaiya college of engineering', nan, nan, nan, 'vtu',
       'mumbai university', nan, 'ict mumbai', 'university of mumbai',
       'tcet', 'vtu', 'nit', 'mit-coe', 'fr agnel, vashi, mumbai',
       'mumbai university', 'mumbai university', 'vit, pune',
       'mumbai university', 'vit , vellore', 'vtu', 'mumbai university',
       'pune university', 'psg college of technology',
       'k.j. somaiya college of engineering', nan, nan, 'da-iict', nan,
       'vtu', nan,
       'shri ramdeobaba college of engineering and management', 'uvce',
       'anna university', nan, 'university of pune', 'vit university',
       'veermata jijabai technological institute', 'anna university',
       'government college of engineering and research, awasari, pune',
       'ip university', 'mumbai university', 'r.t.m.n.u', nan, nan,
       'rnsit bangalore', 'vtu', 'rvce', nan,
       'bangalore institute of technology',
       'kumaraguru college of technology', 'mumbai university',
       'mumbai university', 'rgpv', 'gtu', 'sathyabama university',
       'charusat', 'mumbai university', 'pes university, bengaluru', nan,
       'mumbai university', 'mumbai university', 'university of mumbai',
       'msrit', 'pune university', 'mumbai university', 'mumbai',
       'jss noida', 'mumbai university', nan, nan, 'shah and anchor', nan,
       'gujarat technical university', 'mumbai university', nan,
       'mumbai university', 'anna university', 'manipal university',
       'sjce', 'vjti', 'vtu belgaum', 'vtu', 'mumbai university',
       'srm university , chennai', nan, nan, nan,
       'chhattisgarh swami vivekanand technical university', 'extc',
       'cusat', nan, 'nagpur university', nan, 'vtu', 'mumbai', 'vtu',
       'ms ramaiah institute of technology', 'mumbai university', nan,
       'mumbai university', 'st. francis institute of technology', nan,
       'mumbai university', nan, 'mumbai university',
       'atharva college of engineering', nan,
       'maharaja sayajirao university of baroda',
       'jss academy of technical education', 'nmims', 'vtu', nan,
       'sardar patel institute of technology', nan, nan, nan,
       'medicaps university', 'gec bhuj', 'mumbai university', 'gtu', nan,
       nan, 'university of mumbai (thakur college of engineering)',
       'sri venkateswara college of engineering, chennai', 'ddu',
       'vishwakarma institute of technology',
       'sikkim manipal institute of technology', nan,
       'shivaji university', 'nirma university', 'vtu', nan, 'vjti',
       'rgpv', 'd j sanghvi', 'nmims mpstme', nan, nan, nan, 'ptu', nan,
       nan, 'delhi technological university', 'mumbai university',
       'mumbai university', nan, 'mumbai university', 'mumbai univ',
       'mumbai university', 'k. j. somaiya college of engineering',
       'st. francis institute of technology', 'mumbai university', 'tsec',
       'm s ramaiah it ,bangalore', 'karpagam university', 'gtu', nan,
       nan, 'snell college of  engineering', nan, 'mumbai university',
       nan, 'university of mumbai', 'pune university (vit)',
       'chameli devi school of engineering',
       'sies graduate school of technology',
       'college of engineering guindy,anna univ', nan,
       'manipal institute of technology', 'k l university',
       'pune university',
       'mumbai university (sies graduate school of technology)',
       'mumbai university', 'vishwakarma institute of technology, pune',
       nan, nan, nan, 'rcoem, nagpur', nan, nan, 'vtu',
       'university of pune', nan, 'bms college of engineering',
       'thadomal shahani engineering college( mumbai university)',
       'rajiv gandhi proudyogiki vishwavidyalaya',
       'national institute of technology warangal',
       'mumbai university (dj sanghvi coe)', nan, 'mumbai university',
       'charotar university', 'ggsipu', 'amrita',
       'national institute of engineering mysore',
       'bms institute of technology', 'university of mumbai',
       'goa university',
       'sardar patel institute of technology.( mumbai university)',
       'pesit', 'dharmsinh desai university, nadiad', 'iit bombay',
       'universiy of pune', 'nmims', 'iet-davv',
       'mukesh patel school of technology management and engineering',
       'vjti', 'nit trichy', 'manipal university', 'mumbai university',
       'kiit university', nan,
       'yadavrao tasgaonkar college of engg & mgmt',
       'dhirubhai ambani institute of information and communication technology',
       'kiit university', 'mumbai university', 'sakec',
       'vidyalankar institute of technology', 'dj sanghvi',
       'chitkara university', 'bangalore institute of technology(vtu)',
       'alliance university', nan, 'mu', 'mumbai university', 'vesit',
       'sndt university', 'thakur college', 'nit trichy',
       'college of engineering pune', 'mumbai university',
       'mumbai university', 'nmims university', nan, nan,
       'indus university', nan, 'rtm nagpur university',
       'fr. crce, mumbai university', nan,
       'thadomal shahani engineering college', 'vtu',
       'kiit university , bhubaneshwar', 'mumbai university', 'iet davv',
       'bits pilani', 'mumbai university', nan,
       'thakur college of engineering and technology', nan,
       'mumbai university', nan, nan, 'pune university',
       'sardar patel college of engineering.(mumbai university)',
       'vit, pune', 'university of mumbai', nan,
       'sardar patel college of engineering (spce)',
       'university of mumbai', 'bangalore institute of technology',
       'university of mumbai', 'manipal institute of technology', 'vjti',
       'msrit', 'north eastern university',
       'ms ramaiah institute of technology', 'pesit', nan,
       'mumbai university', 'g.b.p.u.a.t', nan,
       'pimpri chinchwad college of engineering', nan,
       'ip university, delhi', nan, nan,
       'pandit deendayal petroleum university', 'university of pune',
       'mumbai university', nan, 'bamu', 'kj somaiya cllg of engg',
       'sastra university', 'mumbai university', 'mumbai university',
       'pune university', 'institute of chemical technology',
       'ramrao adik institute of technology', nan, 'mumbai university',
       nan, nan, 'manipal institute of technology', 'solapur university',
       'government college of engineering aurangabad', nan, 'bput', nan,
       'kiit university', 'mechanical engineering', 'mumbai university',
       nan, nan, 'jiit', nan, 'solapur university',
       'university of mumbai', 'uvce', nan, 'amrita university', nan,
       'vtu', nan, nan, 'university of pune', nan,
       'manav rachna university', 'sardar patel college of engineering',
       nan, 'pune university', nan, 'nit-trichy',
       'vit university, vellore', 'mumbai university',
       'vellore institute of technology', 'university of mumbai',
       'mumbai university', 'pune university', 'jssate',
       'm.s. ramaiah institute of technology, bangalore',
       'university of pune', nan,
       'thadomal shahani engineering college(tsec)',
       'bms college of engineering', nan, nan,
       'ad patel institute of technology', nan, 'vesit', nan, nan,
       'manav rachna university', 'svce', 'anna university', nan,
       'kumaraguru college of technology, coimbatore', nan,
       'amrita vishwa vidyapeetham', nan, 'rv college of engineering',
       'zz', nan, 'srcoem nagpur', 'gujarat technological university',
       nan, 'mumbai university', nan, 'sastra', 'g.b.p.u.a.t, pantnagar',
       nan, 'gujarat university', nan, 'ip university',
       'gujarat technological university', 'daviet', nan, nan, nan,
       'rgpv bhopal', nan, 'anna university', nan, 'anna university. jce',
       nan, nan, nan, 'dharmsinh desai university',
       'jaipur engineering college and research center', nan, nan, nan],
      dtype=object)

In [65]:
budd_new[budd_new.isnull().any(axis=1)]

,gender,hometown,current_city,need_roommate,open_to_other_branch,undergrad_uni,work_ex,dist_from_uni,person_per_room,apt_type,...,MS Data Science,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others
0,0,mumbai,mumbai,Yes,Yes,mumbai university,3.50,<3,"1, 2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,dr. ambedkar institute of technology.,1.80,<3,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
5,1,mangalore,pune,Yes,Yes,NaN,2.80,<3,1,"1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,msrit,3.00,<10,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0
7,1,indore,mumbai,Yes,Yes,NaN,3.50,<5,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
8,0,bangalore,chennai,Yes,Yes,government college of technology,0.60,<3,"4, I can stay in Hall too",2 BHK,...,0,0,0,1,0,0,0,0,0,0
9,0,pune,pune,Yes,Yes,NaN,2.50,<3,"3, 4","2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
10,0,bangalore,mumbai,Yes,Yes,vtu,2.50,<1,2,2 BHK,...,0,0,0,0,0,0,0,0,0,1
11,0,hyderabad,hyderabad,Yes,Yes,jntu,0.80,<10,"1, 2, 3","2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,NaN,0.00,<3,1,2 BHK,...,0,0,0,0,0,0,0,0,0,0
13,0,amravati,nagpur,Yes,Yes,shri ramdeobaba college of engineering and man...,0.00,<5,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
15,1,pune,pune,Yes,Yes,pu,0.00,<3,2,"Studio, 1BHK",...,0,0,0,0,0,0,0,0,0,0
16,0,chennai,chennai,Yes,Yes,madras institute of technology,3.50,<5,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,vjti,1.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,1,0,0,0,0,0,0,0,0
18,0,nagpur,nagpur,Yes,Yes,nagpur university,0.00,<5,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
19,0,vadodara,vadodara,Yes,Yes,"svit, vasad, gujarat (gtu",0.30,<3,"2, 4",2 BHK,...,0,0,1,0,0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,NaN,0.00,<3,2,"2 BHK, 3BHK",...,0,0,0,1,0,0,0,0,0,0
22,0,mumbai,mumbai,Yes,Yes,mumbai university,0.00,<5,"1, 2","Studio, 1BHK",...,0,0,0,0,0,0,1,0,0,0
23,0,bangalore,bangalore,Yes,Yes,"pesit south campus, vtu",2.00,<5,"3, 4","Studio, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
24,0,mumbai,mumbai,Yes,Yes,NaN,0.40,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
25,0,sirsa,pune,Yes,Yes,mdu,2.20,<5,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
26,0,pune,pune,Yes,Yes,NaN,0.00,<5,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
27,0,mumbai,mumbai,Yes,Yes,NaN,0.30,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
28,0,pune,pune,Yes,Yes,vit pune,0.00,<5,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,1,0,0,0,0
29,0,lucknow,raipur,Yes,No,national institute of technology raipur,0.00,<5,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
30,0,chennai,chennai,Yes,Yes,NaN,3.00,<3,4,"2 BHK, 3BHK",...,0,1,0,0,0,0,0,0,0,0
31,0,kolkata,bangalore,Yes,No,biju patnaik university of technology,3.50,<5,"2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
34,1,margao goa,goa,Yes,Yes,vit vellore,1.00,<3,"2, 3",2 BHK,...,0,1,0,0,0,0,0,0,0,0
35,0,mumbai,mumbai,Yes,Yes,mumbai university,1.80,<10,"1, 2","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
36,0,hyderabad,hyderabad,Yes,Yes,NaN,0.00,<10,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,0,chennai,chennai,No,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
488,0,coimbatore,coimbatore,Yes,Yes,amrita vishwa vidyapeetham,0.00,<3,4,"1BHK, 2 BHK",...,0,0,0,0,1,0,0,0,0,0
489,0,mumbai,mumbai,Yes,Yes,NaN,0.00,<3,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
491,0,zz,zz,Yes,Yes,zz,9.00,<3,1,Studio,...,0,0,0,0,0,0,0,0,1,0
492,0,pune,pune,Yes,Yes,NaN,4.00,<3,"3, 4","1BHK, 2 BHK",...,0,0,0,0,0,1,0,0,0,0
493,0,nagpur,nagpur,Yes,Yes,srcoem nagpur,1.00,<3,"1, 2",2 BHK,...,0,0,0,1,0,0,0,0,0,0
495,0,mumbai,mumbai,Yes,Yes,NaN,0.00,<5,1,"2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
496,0,up,mumbai,Yes,Yes,mumbai university,0.40,<3,1,"2 BHK, 3BHK, 4 BHK",...,0,0,0,0,1,0,0,0,0,0
497,0,mumbai,mumbai,Yes,Yes,NaN,1.00,<3,"3, 4","1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,sastra,1.08,<3,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
499,0,dehradun,dehradun,Yes,Yes,"g.b.p.u.a.t, pantnagar",1.00,<3,1,1BHK,...,0,0,0,0,0,0,0,0,0,0
500,0,indore,indore,Yes,Yes,NaN,0.00,<3,2,"1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
501,0,vadodara,vadodara,Yes,Yes,gujarat university,6.00,<5,4,2 BHK,...,0,0,0,0,0,0,1,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,NaN,0.30,<3,2,"2 BHK, 3BHK",...,0,0,0,0,1,0,0,0,0,0
504,0,mehsana,surat,Yes,Yes,gujarat technological university,0.00,<3,"1, 2, 3, 4, I can stay in Hall too",2 BHK,...,0,0,0,0,0,0,0,1,0,0
506,0,surat,surat,Yes,Yes,NaN,0.00,<5,2,"1BHK, 2 BHK",...,0,0,1,0,0,0,0,0,0,0
507,0,mumbai,mumbai,Yes,Yes,NaN,0.00,<1,"2, I can stay in Hall too",2 BHK,...,0,0,0,0,0,0,1,0,0,0
508,1,mumbai,mumbai,Yes,Yes,NaN,3.00,<1,4,"1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
509,0,indore,navi mumbai,Yes,Yes,rgpv bhopal,3.00,<3,I can stay in Hall too,2 BHK,...,0,0,0,0,0,0,1,0,0,0
510,0,chennai,boston,Yes,Yes,NaN,4.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
512,0,hyderabad,hyderabad,Yes,Yes,NaN,0.00,<3,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
513,0,chennai,chennai,Yes,No,anna university. jce,5.00,<5,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
514,0,indore,indore,Yes,Yes,NaN,0.00,<3,"1, 2","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,NaN,1.00,<3,2,"1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
516,0,mangalore,india,Yes,Yes,NaN,0.00,<3,"2, 3, 4","1BHK, 2 BHK, 3BHK",...,0,0,1,0,0,0,0,0,0,0
517,0,rajkot,mumbai,Yes,Yes,dharmsinh desai university,3.00,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
518,0,jaipur,jaipur,Yes,No,jaipur engineering college and research center,3.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
519,0,navi mumbai,navi mumbai,Yes,Yes,NaN,4.00,<3,"1, 2","2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
520,0,raipur,raipur,Yes,Yes,NaN,2.00,<3,"2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
521,1,indore,indore,Yes,Yes,NaN,0.00,<10,1,"Studio, 1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0

In [68]:
budd_new[budd_new['current_city'] == 'bangalore']

,gender,hometown,current_city,need_roommate,open_to_other_branch,undergrad_uni,work_ex,dist_from_uni,person_per_room,apt_type,...,MS Data Science,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others
1,0,patna,bangalore,Yes,Yes,vtu,3.50,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,dr. ambedkar institute of technology.,1.80,<3,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,msrit,3.00,<10,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,NaN,0.00,<3,1,2 BHK,...,0,0,0,0,0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,NaN,0.00,<3,2,"2 BHK, 3BHK",...,0,0,0,1,0,0,0,0,0,0
23,0,bangalore,bangalore,Yes,Yes,"pesit south campus, vtu",2.00,<5,"3, 4","Studio, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
31,0,kolkata,bangalore,Yes,No,biju patnaik university of technology,3.50,<5,"2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
38,0,patna,bangalore,Yes,Yes,sri bhagawan mahaveer jain college of engineering,2.00,<3,"1, 2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
50,0,kalaburagi,bangalore,Yes,Yes,visvesvaraya technological university,2.60,<5,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
51,0,udupi karnataka,bangalore,Yes,Yes,vtu,2.60,<5,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
52,0,kalaburagi,bangalore,Yes,Yes,NaN,2.60,<5,2,"1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
56,0,bangalore,bangalore,Yes,Yes,sit,2.50,<1,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
61,0,thanjavur,bangalore,Yes,Yes,sastra university,1.70,<5,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
64,0,delhi,bangalore,Yes,Yes,manipal institute of technology,0.90,<3,"2, 3","2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
66,1,bangalore,bangalore,Yes,Yes,bit,2.00,<5,2,"2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
69,0,bangalore,bangalore,Yes,No,vtu,1.50,<3,"3, 4","1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
70,1,bangalore,bangalore,Yes,Yes,b.n.m it (vtu),1.50,<3,2,"2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,1,0,0,0,0
73,0,gulbarga,bangalore,Yes,Yes,vtu belgaum,3.50,<10,"1, 2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
77,0,bangalore,bangalore,Yes,Yes,NaN,0.00,<1,1,"1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
81,0,pondicherry,bangalore,Yes,Yes,pondicherry engineering college,2.00,<10,"3, 4, I can stay in Hall too","2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
88,1,lucknow,bangalore,Yes,Yes,NaN,2.50,<1,"2, 3","1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
89,1,tamilnadu,bangalore,Yes,Yes,amrita school of engineering,0.00,<10,2,"2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
92,0,"thrissur, kerala, india",bangalore,Yes,Yes,"vit university, vellore",2.00,<1,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
104,0,bangalore,bangalore,Yes,Yes,rns institute of technology,1.80,<5,"2, 3, I can stay in Hall too",2 BHK,...,0,0,0,0,0,0,0,0,0,0
107,1,uttar pradesh,bangalore,Yes,Yes,university visveswaraya college of engineering,2.00,<3,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK",...,1,0,0,0,0,0,0,0,0,0
110,0,bangalore,bangalore,Yes,Yes,NaN,3.00,<5,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
129,1,bangalore,bangalore,Yes,Yes,vtu (atria institute of technology),3.00,<3,"2, 3, I can stay in Hall too","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
133,0,kolkata,bangalore,Yes,Yes,dayananda sagar college,2.70,<3,"2, I can stay in Hall too","1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
143,0,bangalore,bangalore,Yes,Yes,NaN,2.00,<3,4,2 BHK,...,0,0,0,0,0,0,0,0,0,0
145,0,bangalore,bangalore,Yes,Yes,vtu,2.60,<3,I can stay in Hall too,"Studio, 1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,0,bangalore,bangalore,Yes,Yes,NaN,2.00,<3,3,"2 BHK, 3BHK",...,0,0,0,0,0,0,1,0,0,0
283,1,delhi,bangalore,Yes,Yes,delhi technological university,2.00,<5,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
286,1,bangalore,bangalore,Yes,Yes,NaN,1.40,<3,"2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
294,1,bangalore,bangalore,Yes,Yes,"m s ramaiah it ,bangalore",3.00,<3,2,"1BHK, 2 BHK",...,0,0,0,0,0,0,1,0,0,0
297,1,lucknow,bangalore,Yes,Yes,NaN,2.60,<10,"1, 2, 3",2 BHK,...,0,0,0,0,0,0,1,0,0,0
319,1,mysore,bangalore,Yes,Yes,NaN,2.00,<3,2,"1BHK, 2 BHK",...,0,1,0,0,0,0,0,0,0,0
324,0,bangalore,bangalore,Yes,Yes,bms college of engineering,2.50,<10,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,1,0,0,0,0,0,0,0,0,0
329,0,meerut,bangalore,Yes,Yes,NaN,2.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
335,0,bangalore,bangalore,Yes,Yes,bms institute of technology,1.50,<3,2,"1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
339,0,mangalore,bangalore,Yes,Yes,pesit,3.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
360,0,sakaleshpur,bangalore,Yes,Yes,bangalore institute of technology(vtu),6.00,<3,"2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
362,0,ghaziabad,bangalore,Yes,Yes,NaN,2.00,<5,"1, 2","Studio, 1BHK, 2 BHK, 3BHK",...,1,0,0,0,0,0,0,0,0,0
369,1,mumbai,bangalore,Yes,Yes,college of engineering pune,3.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
376,0,bangalore,bangalore,Yes,Yes,NaN,3.00,<3,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
378,0,rajkot,bangalore,Yes,Yes,"fr. crce, mumbai university",1.00,<1,"1, 2","3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,0
381,0,bangalore,bangalore,Yes,Yes,vtu,2.60,<3,"2, 3, 4","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
400,0,sakaleshpur,bangalore,Yes,Yes,bangalore institute of technology,6.00,<1,"2, I can stay in Hall too","1BHK, 2 BHK, 3BHK",...,0,0,0,0,0,0,0,0,0,0
406,0,bangalore,bangalore,Yes,Yes,ms ramaiah institute of technology,0.00,<3,"1, 2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
407,1,bangalore,bangalore,Yes,Yes,pesit,0.60,<1,2,"Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,1
451,1,hyderabad,bangalore,Yes,Yes,NaN,2.00,<5,"1, 2","2 BHK, 3BHK",...,0,0,0,1,0,0,0,0,0,0
452,0,mandya,bangalore,Yes,Yes,vtu,2.80,<1,"3, 4","1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,1
459,0,coimbatore,bangalore,Yes,Yes,NaN,2.00,<3,"3, 4","Studio, 1BHK, 2 BHK, 3BHK",...,0,0,0,1,0,0,0,0,0,0
463,0,guntur,bangalore,Yes,Yes,"vit university, vellore",0.00,<5,"3, 4","2 BHK, 3BHK, 4 BHK",...,1,0,0,0,0,0,0,0,0,0
469,1,bangalore,bangalore,Yes,Yes,jssate,1.60,<10,"1, 2","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,1,0,0,0,0,0,0
474,0,belgaum,bangalore,Yes,Yes,bms college of engineering,0.00,<3,"3, 4","2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,0,0,0,1
477,1,vaododara,bangalore,Yes,No,ad patel institute of technology,2.00,<5,"1, 2, 3","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0
481,0,trivandrum,bangalore,Yes,Yes,NaN,3.00,<3,"1, 2","1BHK, 2 BHK, 3BHK",...,0,0,0,0,1,0,0,0,0,0
484,0,chennai,bangalore,Yes,Yes,anna university,2.50,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",...,0,0,0,0,0,0,1,0,0,0
486,0,coimbatore,bangalore,Yes,Yes,"kumaraguru college of technology, coimbatore",2.00,<3,"4, I can stay in Hall too","1BHK, 2 BHK",...,0,0,0,1,0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,sastra,1.08,<3,"1, 2","Studio, 1BHK, 2 BHK",...,0,0,0,0,0,0,0,0,0,0

In [69]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             9
undergrad_uni                                  138
work_ex                                          9
dist_from_uni                                    9
person_per_room                                  9
apt_type                                         9
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
dtype: int64

In [74]:
pd.value_counts(budd_new['open_to_other_branch'])

Yes    477
No      36
Name: open_to_other_branch, dtype: int64

In [31]:
pd.(budd_new['open_to_other_branch'])

9

In [32]:
budd_new.open_to_other_branch = budd_new.open_to_other_branch.fillna('Yes')

In [34]:
budd_new.open_to_other_branch.isnull().sum()

0

In [35]:
budd_new.undergrad_uni.value_counts()

mumbai university                                            55
vtu                                                          19
university of mumbai                                         12
pune university                                              12
university of pune                                            6
vjti                                                          6
anna university                                               5
manipal institute of technology                               4
gujarat technological university                              3
dharmsinh desai university                                    3
indus university                                              3
gtu                                                           3
nagpur university                                             3
sastra university                                             3
kiit university                                               3
mumbai                                                        3
nmims                                                         3
nit trichy                                                    3
msrit                                                         3
bms college of engineering                                    2
pesit                                                         2
vit vellore                                                   2
vit university, vellore                                       2
vellore institute of technology                               2
manav rachna university                                       2
jiit                                                          2
solapur university                                            2
shri ramdeobaba college of engineering and management         2
nirma university                                              2
rgpv                                                          2
                                                             ..
sastra                                                        1
national institute of technology warangal                     1
gujarat university                                            1
chhattisgarh swami vivekanand technical university            1
thadomal shahani engineering college                          1
vishwakarma institute of technology, pune                     1
nmims university                                              1
kumaraguru college of technology, coimbatore                  1
university visveswaraya college of engineering                1
jssate                                                        1
jaypee instituteof information technology, noida              1
dayananda sagar college                                       1
k.j. somaiya college of engineering                           1
vit university                                                1
thadomal shahani engineering college( mumbai university)      1
rns institute of technology                                   1
sies gst, mumbai university                                   1
bit                                                           1
daviet                                                        1
sardar patel institute of technology.( mumbai university)     1
dwarkadas j. sanghvi college of engineering                   1
sit                                                           1
chitkara university                                           1
mu                                                            1
vjti, mumbai                                                  1
mumbai university (sies graduate school of technology)        1
rgpv bhopal                                                   1
rajiv gandhi institute of technology                          1
g.b.p.u.a.t                                                   1
sardar patel college of engineering (spce)                    1
Name: undergrad_uni, Length: 224, dtype: int64

In [36]:
budd_new = budd_new.drop(labels=['undergrad_uni'], axis = 1)

In [39]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          9
dist_from_uni                                    9
person_per_room                                  9
apt_type                                         9
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
dtype: int64

In [41]:
np.average(budd_new.work_ex)

nan

In [45]:
budd_new.work_ex.value_counts()

0.000    177
2.000     75
1.000     52
3.000     32
1.500     22
2.500     18
5.000     12
1.800     11
0.500     10
3.500      9
0.600      7
2.600      6
1.700      6
2.800      6
0.700      5
4.000      5
0.800      5
0.300      4
0.900      4
6.000      4
0.400      3
1.400      3
2.700      3
2.400      3
1.600      3
2.200      3
3.800      2
9.000      2
0.750      2
1.100      2
4.500      2
2.100      2
3.600      1
1.300      1
0.200      1
6.500      1
1.750      1
0.250      1
3.750      1
3.900      1
1.080      1
0.160      1
0.167      1
2.300      1
2.750      1
Name: work_ex, dtype: int64

In [46]:
# Get non null values, average them and change work ex to avg work ex value

In [50]:
work_ex_avg = np.average(budd_new.work_ex[budd_new.work_ex.notnull()])

In [51]:
budd_new.work_ex = budd_new.work_ex.fillna(work_ex_avg)

In [52]:
budd_new.work_ex.isnull().sum()

0

In [ ]:
# Get non null values, average them and change distance to avg distance value

In [108]:
# Change distance to int
budd_new.dist_from_uni[budd_new.dist_from_uni.notnull()] = \
[int(d[1:]) for d in budd_new.dist_from_uni[budd_new.dist_from_uni.notnull()]]

TypeError: 'int' object is not subscriptable

In [99]:
budd_new.dist_from_uni.isnull().sum()

9

In [92]:
budd_new.set_value(206, 'dist_from_uni', '<10')

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,person_per_room,apt_type,rent_budget,...,MS Data Science,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others
0,0,mumbai,mumbai,Yes,Yes,3.50,<3,"1, 2, 3","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,1.80,<3,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,<5,"2, 3, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
4,0,chennai,chennai,No,Yes,2.00,<10,"2, 3","Studio, 1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
5,1,mangalore,pune,Yes,Yes,2.80,<3,1,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,<10,"1, 2","Studio, 1BHK, 2 BHK",< $400,...,0,0,0,1,0,0,0,0,0,0
7,1,indore,mumbai,Yes,Yes,3.50,<5,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,0,0,0,0,0,0,0
8,0,bangalore,chennai,Yes,Yes,0.60,<3,"4, I can stay in Hall too",2 BHK,< $500,...,0,0,0,1,0,0,0,0,0,0
9,0,pune,pune,Yes,Yes,2.50,<3,"3, 4","2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
10,0,bangalore,mumbai,Yes,Yes,2.50,<1,2,2 BHK,< $550,...,0,0,0,0,0,0,0,0,0,1
11,0,hyderabad,hyderabad,Yes,Yes,0.80,<10,"1, 2, 3","2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,<3,1,2 BHK,< $550,...,0,0,0,0,0,0,0,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,<5,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,1,0,0,0,0,0,0
14,1,d,h,Yes,Yes,5.00,<1,2,Studio,< $500,...,0,0,0,0,0,0,0,0,0,0
15,1,pune,pune,Yes,Yes,0.00,<3,2,"Studio, 1BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
16,0,chennai,chennai,Yes,Yes,3.50,<5,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,1,0,0,0,0,0,0,0,0
18,0,nagpur,nagpur,Yes,Yes,0.00,<5,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
19,0,vadodara,vadodara,Yes,Yes,0.30,<3,"2, 4",2 BHK,< $550,...,0,0,1,0,0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,<3,2,"2 BHK, 3BHK",< $450,...,0,0,0,1,0,0,0,0,0,0
21,0,kochi,kochi,Yes,Yes,1.80,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
22,0,mumbai,mumbai,Yes,Yes,0.00,<5,"1, 2","Studio, 1BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
23,0,bangalore,bangalore,Yes,Yes,2.00,<5,"3, 4","Studio, 2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
24,0,mumbai,mumbai,Yes,Yes,0.40,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
25,0,sirsa,pune,Yes,Yes,2.20,<5,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
26,0,pune,pune,Yes,Yes,0.00,<5,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
27,0,mumbai,mumbai,Yes,Yes,0.30,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
28,0,pune,pune,Yes,Yes,0.00,<5,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,1,0,0,0,0
29,0,lucknow,raipur,Yes,No,0.00,<5,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,<3,"3, 4","1BHK, 2 BHK",< $550,...,0,0,0,0,0,1,0,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,<3,"1, 2",2 BHK,< $500,...,0,0,0,1,0,0,0,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,<5,1,"2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,1,0,0,0
496,0,up,mumbai,Yes,Yes,0.40,<3,1,"2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,0,1,0,0,0,0,0
497,0,mumbai,mumbai,Yes,Yes,1.00,<3,"3, 4","1BHK, 2 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,<3,"1, 2","Studio, 1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
499,0,dehradun,dehradun,Yes,Yes,1.00,<3,1,1BHK,< $500,...,0,0,0,0,0,0,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,<3,2,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,<5,4,2 BHK,< $500,...,0,0,0,0,0,0,1,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,<3,2,"2 BHK, 3BHK",< $500,...,0,0,0,0,1,0,0,0,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,<3,"1, 2","2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
504,0,mehsana,surat,Yes,Yes,0.00,<3,"1, 2, 3, 4, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,0,0,1,0,0
505,1,jalandhar,jalandhar,Yes,Yes,0.00,<1,3,"Studio, 2 BHK, 3BHK",< $400,...,0,0,0,0,0,0,0,0,0,1
506,0,surat,surat,Yes,Yes,0.00,<5,2,"1BHK, 2 BHK",< $550,...,0,0,1,0,0,0,0,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,<1,"2, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,0,1,0,0,0
508,1,mumbai,mumbai,Yes,Yes,3.00,<1,4,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,<3,I can stay in Hall too,2 BHK,< $550,...,0,0,0,0,0,0,1,0,0,0
510,0,chennai,boston,Yes,Yes,4.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
511,0,hosur,hosur,Yes,Yes,2.00,<10,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
512,0,hyderabad,hyderabad,Yes,Yes,0.00,<3,"1, 2","Studio, 1BHK, 2 BHK",< $450,...,0,0,0,0,0,0,0,0,0,0
513,0,chennai,chennai,Yes,No,5.00,<5,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
514,0,indore,indore,Yes,Yes,0.00,<3,"1, 2","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,<3,2,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,<3,"2, 3, 4","1BHK, 2 BHK, 3BHK",< $700,...,0,0,1,0,0,0,0,0,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
518,0,jaipur,jaipur,Yes,No,3.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,<3,"1, 2","2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
520,0,raipur,raipur,Yes,Yes,2.00,<3,"2, 3","1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
521,1,indore,indore,Yes,Yes,0.00,<10,1,"Studio, 1BHK, 2 BHK",< $550,...,0,0,0,1,0,0,0,0,0,0

In [93]:
budd_new.set_value(130, 'dist_from_uni', '<10')

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,person_per_room,apt_type,rent_budget,...,MS Data Science,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others
0,0,mumbai,mumbai,Yes,Yes,3.50,<3,"1, 2, 3","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,1.80,<3,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,<5,"2, 3, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
4,0,chennai,chennai,No,Yes,2.00,<10,"2, 3","Studio, 1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
5,1,mangalore,pune,Yes,Yes,2.80,<3,1,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,<10,"1, 2","Studio, 1BHK, 2 BHK",< $400,...,0,0,0,1,0,0,0,0,0,0
7,1,indore,mumbai,Yes,Yes,3.50,<5,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,0,0,0,0,0,0,0
8,0,bangalore,chennai,Yes,Yes,0.60,<3,"4, I can stay in Hall too",2 BHK,< $500,...,0,0,0,1,0,0,0,0,0,0
9,0,pune,pune,Yes,Yes,2.50,<3,"3, 4","2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
10,0,bangalore,mumbai,Yes,Yes,2.50,<1,2,2 BHK,< $550,...,0,0,0,0,0,0,0,0,0,1
11,0,hyderabad,hyderabad,Yes,Yes,0.80,<10,"1, 2, 3","2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,<3,1,2 BHK,< $550,...,0,0,0,0,0,0,0,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,<5,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,1,0,0,0,0,0,0
14,1,d,h,Yes,Yes,5.00,<1,2,Studio,< $500,...,0,0,0,0,0,0,0,0,0,0
15,1,pune,pune,Yes,Yes,0.00,<3,2,"Studio, 1BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
16,0,chennai,chennai,Yes,Yes,3.50,<5,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,<3,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,1,0,0,0,0,0,0,0,0
18,0,nagpur,nagpur,Yes,Yes,0.00,<5,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
19,0,vadodara,vadodara,Yes,Yes,0.30,<3,"2, 4",2 BHK,< $550,...,0,0,1,0,0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,<3,2,"2 BHK, 3BHK",< $450,...,0,0,0,1,0,0,0,0,0,0
21,0,kochi,kochi,Yes,Yes,1.80,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
22,0,mumbai,mumbai,Yes,Yes,0.00,<5,"1, 2","Studio, 1BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
23,0,bangalore,bangalore,Yes,Yes,2.00,<5,"3, 4","Studio, 2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
24,0,mumbai,mumbai,Yes,Yes,0.40,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
25,0,sirsa,pune,Yes,Yes,2.20,<5,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
26,0,pune,pune,Yes,Yes,0.00,<5,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
27,0,mumbai,mumbai,Yes,Yes,0.30,<5,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
28,0,pune,pune,Yes,Yes,0.00,<5,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,1,0,0,0,0
29,0,lucknow,raipur,Yes,No,0.00,<5,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,<3,"3, 4","1BHK, 2 BHK",< $550,...,0,0,0,0,0,1,0,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,<3,"1, 2",2 BHK,< $500,...,0,0,0,1,0,0,0,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,<3,"1, 2, 3","1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,<5,1,"2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,1,0,0,0
496,0,up,mumbai,Yes,Yes,0.40,<3,1,"2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,0,1,0,0,0,0,0
497,0,mumbai,mumbai,Yes,Yes,1.00,<3,"3, 4","1BHK, 2 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,<3,"1, 2","Studio, 1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
499,0,dehradun,dehradun,Yes,Yes,1.00,<3,1,1BHK,< $500,...,0,0,0,0,0,0,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,<3,2,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,<5,4,2 BHK,< $500,...,0,0,0,0,0,0,1,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,<3,2,"2 BHK, 3BHK",< $500,...,0,0,0,0,1,0,0,0,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,<3,"1, 2","2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
504,0,mehsana,surat,Yes,Yes,0.00,<3,"1, 2, 3, 4, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,0,0,1,0,0
505,1,jalandhar,jalandhar,Yes,Yes,0.00,<1,3,"Studio, 2 BHK, 3BHK",< $400,...,0,0,0,0,0,0,0,0,0,1
506,0,surat,surat,Yes,Yes,0.00,<5,2,"1BHK, 2 BHK",< $550,...,0,0,1,0,0,0,0,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,<1,"2, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,0,1,0,0,0
508,1,mumbai,mumbai,Yes,Yes,3.00,<1,4,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,<3,I can stay in Hall too,2 BHK,< $550,...,0,0,0,0,0,0,1,0,0,0
510,0,chennai,boston,Yes,Yes,4.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
511,0,hosur,hosur,Yes,Yes,2.00,<10,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
512,0,hyderabad,hyderabad,Yes,Yes,0.00,<3,"1, 2","Studio, 1BHK, 2 BHK",< $450,...,0,0,0,0,0,0,0,0,0,0
513,0,chennai,chennai,Yes,No,5.00,<5,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
514,0,indore,indore,Yes,Yes,0.00,<3,"1, 2","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,<3,2,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,<3,"2, 3, 4","1BHK, 2 BHK, 3BHK",< $700,...,0,0,1,0,0,0,0,0,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,<3,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
518,0,jaipur,jaipur,Yes,No,3.00,<1,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,<3,"1, 2","2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
520,0,raipur,raipur,Yes,Yes,2.00,<3,"2, 3","1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,1,0,0,0
521,1,indore,indore,Yes,Yes,0.00,<10,1,"Studio, 1BHK, 2 BHK",< $550,...,0,0,0,1,0,0,0,0,0,0

In [106]:
dist_avg = np.sum(budd_new.dist_from_uni[budd_new.dist_from_uni.notnull()])/len(budd_new.dist_from_uni\
                                                                                [budd_new.dist_from_uni.notnull()])

In [107]:
dist_avg

4.046783625730995

In [112]:
budd_new['dist_from_uni'] = budd_new['dist_from_uni'].apply(float)

In [116]:
budd_new.dist_from_uni = budd_new.dist_from_uni.fillna(dist_avg)

In [117]:
budd_new.dist_from_uni.isnull().sum()

0

In [119]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
person_per_room                                  9
apt_type                                         9
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
dtype: int64

In [123]:
budd_new.person_per_room[budd_new.person_per_room.notnull()] = int(\
                                                                   max(budd_new.person_per_room[budd_new.person_per_room.notnull()]))

3

In [124]:
int(max(budd_new.person_per_room[budd_new.person_per_room.notnull()]))

TypeError: '>' not supported between instances of 'int' and 'str'

In [155]:
hall_ind = 'I can stay in Hall too'
hall_yes_no = [1 if hall_ind in str(d) else 0 for d in budd_new.person_per_room]

In [156]:
budd_new['hall_yes_no'] = hall_yes_no

In [147]:
for j in (budd_new.person_per_room):
    try:
        if '3' in j:print(j)
    except:
        print(j)

1, 2, 3
1, 2, 3
2
2, 3, I can stay in Hall too
2, 3
1
1
3, 4
2
1, 2, 3
1
2, 3
2
2
1, 2, 3, 4
1
1, 2, 3, 4, I can stay in Hall too
2
3, 4
2, 3, 4, I can stay in Hall too
2
3, 4, I can stay in Hall too
2, 3
1, 2, 3, 4
4
2, 3
1, 2, 3
1
2, 3
1, 2, 3, 4
1
1, 2, 3
2, 3, I can stay in Hall too
3, 4, I can stay in Hall too
1, 2, 3, 4
4
4
2
1, 2, 3, 4
3
1, 2, 3, 4
2
2
2
2, 3, I can stay in Hall too
2
1, 2, 3, 4
2, 3, I can stay in Hall too
2
2, 3
3, 4, I can stay in Hall too
3, 4, I can stay in Hall too
1
2, 3
4
2
1, 2, 3, 4
2
3, 4
2
3, 4
2
1, 2, 3
1
1
1
3
3, 4, I can stay in Hall too
2
4
1
2
1
2, 3
2
2, 3, 4
2, 3, 4
1, 2, 3, 4, I can stay in Hall too
1, 2, 3, 4
2
1, 2, 3, 4
nan
4
2, 3
2, 3, 4
4
2, 3, I can stay in Hall too
3, 4, I can stay in Hall too
2, 3
1, 2, 3, 4
1, 2, 3, 4
2, 3, I can stay in Hall too
2, 3
1, 2, 3
2, 3
3, 4
3, 4
3, 4, I can stay in Hall too
2, 3
2
1, 2, 3, 4
2
1, 2, 3, 4, I can stay in Hall too
3, 4, I can stay in Hall too
1, 2, 3, 4
2, 3
1
2, 3, I can stay in Hall too
1, 2, 3
2, 3
3
1
2, 3
2, 3, 4
1, 2, 3, I can stay in Hall too
3, 4
2
4
2
3, 4
1
2
2, 3
2
2
3, 4
3, 4
2, 3
1, 2, 3
2, 3, 4
4
1
1, 2, 3
2
nan
2
1, 2, 3, 4, I can stay in Hall too
3, 4
2, 3
2
2
1
4
1, 2, 3
1, 2, 3
4
1, 2, 3
2, 3
4
1, 2, 3
4
2, 3
2, 3
1, 2, 3, 4, I can stay in Hall too
2
1, 2, 3, 4
2
3, 4, I can stay in Hall too
2
4
2, 3
2, 3, 4
3, 4
2, 3
2
2
4
1, 2, 3
1, 2, 3, 4
2, 3
3, 4, I can stay in Hall too
4
3, 4, I can stay in Hall too
3, 4
1
1, 3, 4
2, 3
2, 3, 4
1, 2, 3, 4
2
2
2, 3
2, 3
1, 2, 3, 4
3, 4, I can stay in Hall too
3
1
1, 2, 3
2, 3
2, 3
2, 3, 4
3, 4, I can stay in Hall too
1, 2, 3
3, 4
3, 4
1, 2, 3
2
2, 3
2, 3, 4
4
3
2, 3
2, 3
2
2
1
4
3, 4
1, 2, 3, 4
2, 3, 4, I can stay in Hall too
2, 3
3
1
2, 3
2
2
3, 4
2
1
2
1, 2, 3, 4
3
2, 3
2, 3, 4
1
3
2, 3, 4
4
2, 3, 4
1, 2, 3, 4
2, 3, I can stay in Hall too
2, 3, 4
1
3, 4
3, 4
3, 4, I can stay in Hall too
2
1, 2, 3, 4
1, 2, 3, 4, I can stay in Hall too
1, 2, 3
3
nan
2
3, 4
2, 3
1, 2, 3, 4
2
1, 2, 3, 4
4
3, 4, I can stay in Hall too
2
1, 2, 3
2
3, 4
3, 4
2
1
1
1, 2, 3, 4
2
4
1
3
2, 3
2
1, 2, 3, 4, I can stay in Hall too
2
2
2, 3, I can stay in Hall too
1, 2, 3, 4, I can stay in Hall too
1
1
2, 3, 4, I can stay in Hall too
2, 3, 4
2
1, 2, 3, 4
1
2, 3
nan
2, 3
1, 2, 3, 4
2, 3
3, 4, I can stay in Hall too
2, 3
2, 3, I can stay in Hall too
1, 2, 3
2, 3
1, 2, 3, 4, I can stay in Hall too
2
2, 3, I can stay in Hall too
2, 3, 4
2
2
1, 2, 3
1, 2, 3, 4
2, 3
2, 3
2, 3, 4
2, 3, 4
3, 4, I can stay in Hall too
2, 3, 4
2, 3, I can stay in Hall too
2, 3
2
1, 2, 3, 4
2
2, 3, 4
1, 2, 3, 4, I can stay in Hall too
2
1, 2, 3
2, 3, 4, I can stay in Hall too
1, 2, 3, 4
2
2
2
2, 3
1
2, 3, 4
4
1, 2, 3
2
4
2, 3
2, 3
2, 3
2, 3
2
1, 2, 3
4
2
nan
1, 2, 3
4
2, 3
1, 2, 3, 4, I can stay in Hall too
3
3, 4
2, 3, I can stay in Hall too
2, 3, 4, I can stay in Hall too
nan
3, 4
4
3, 4
2, 3
1, 2, 3, 4, I can stay in Hall too
2, 3
2
4
4
2
2
2
1
2, 3
2, 3
3, 4
2, 3
1
2, 3
2
3
3, 4
nan
2, 3, 4
3, 4
1
2, 3, 4
2
1, 2, 3
3, 4, I can stay in Hall too
3, 4
2
3
3, 4
3
1, 2, 3, 4, I can stay in Hall too
1, 2, 3
1
1
3
2
2, 3, 4, I can stay in Hall too
nan
nan
4
1, 2, 3, 4
1
1
3, 4
1, 2, 3
1
1
3, 4
1
2
4
2
1, 2, 3, 4, I can stay in Hall too
3
2
4
2
2
2, 3, 4
2, 3, 4, I can stay in Hall too
2
2, 3
1

In [157]:
budd_new

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,person_per_room,apt_type,rent_budget,...,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others,hall_yes_no
0,0,mumbai,mumbai,Yes,Yes,3.50,3.0,"1, 2, 3","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,3.0,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,1.80,3.0,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,5.0,"2, 3, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,1
4,0,chennai,chennai,No,Yes,2.00,10.0,"2, 3","Studio, 1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
5,1,mangalore,pune,Yes,Yes,2.80,3.0,1,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,10.0,"1, 2","Studio, 1BHK, 2 BHK",< $400,...,0,0,1,0,0,0,0,0,0,0
7,1,indore,mumbai,Yes,Yes,3.50,5.0,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,0,0,0,0,0,0,0
8,0,bangalore,chennai,Yes,Yes,0.60,3.0,"4, I can stay in Hall too",2 BHK,< $500,...,0,0,1,0,0,0,0,0,0,1
9,0,pune,pune,Yes,Yes,2.50,3.0,"3, 4","2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
10,0,bangalore,mumbai,Yes,Yes,2.50,1.0,2,2 BHK,< $550,...,0,0,0,0,0,0,0,0,1,0
11,0,hyderabad,hyderabad,Yes,Yes,0.80,10.0,"1, 2, 3","2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,3.0,1,2 BHK,< $550,...,0,0,0,0,0,0,0,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,5.0,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,1,0,0,0,0,0,0,0
14,1,d,h,Yes,Yes,5.00,1.0,2,Studio,< $500,...,0,0,0,0,0,0,0,0,0,0
15,1,pune,pune,Yes,Yes,0.00,3.0,2,"Studio, 1BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
16,0,chennai,chennai,Yes,Yes,3.50,5.0,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,3.0,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,1,0,0,0,0,0,0,0,0,0
18,0,nagpur,nagpur,Yes,Yes,0.00,5.0,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,1
19,0,vadodara,vadodara,Yes,Yes,0.30,3.0,"2, 4",2 BHK,< $550,...,0,1,0,0,0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,3.0,2,"2 BHK, 3BHK",< $450,...,0,0,1,0,0,0,0,0,0,0
21,0,kochi,kochi,Yes,Yes,1.80,5.0,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
22,0,mumbai,mumbai,Yes,Yes,0.00,5.0,"1, 2","Studio, 1BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
23,0,bangalore,bangalore,Yes,Yes,2.00,5.0,"3, 4","Studio, 2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
24,0,mumbai,mumbai,Yes,Yes,0.40,3.0,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,1
25,0,sirsa,pune,Yes,Yes,2.20,5.0,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
26,0,pune,pune,Yes,Yes,0.00,5.0,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,1
27,0,mumbai,mumbai,Yes,Yes,0.30,5.0,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
28,0,pune,pune,Yes,Yes,0.00,5.0,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,1,0,0,0,0,0
29,0,lucknow,raipur,Yes,No,0.00,5.0,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,5.0,"3, 4","1BHK, 2 BHK",< $550,...,0,0,0,0,1,0,0,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,3.0,"1, 2",2 BHK,< $500,...,0,0,1,0,0,0,0,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,3.0,"1, 2, 3","1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,3.0,1,"2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,1,0,0,0,0
496,0,up,mumbai,Yes,Yes,0.40,1.0,1,"2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,1,0,0,0,0,0,0
497,0,mumbai,mumbai,Yes,Yes,1.00,5.0,"3, 4","1BHK, 2 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,1.0,"1, 2","Studio, 1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
499,0,dehradun,dehradun,Yes,Yes,1.00,1.0,1,1BHK,< $500,...,0,0,0,0,0,0,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,3.0,2,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,1.0,4,2 BHK,< $500,...,0,0,0,0,0,1,0,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,10.0,2,"2 BHK, 3BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,3.0,"1, 2","2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
504,0,mehsana,surat,Yes,Yes,0.00,5.0,"1, 2, 3, 4, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,0,1,0,0,1
505,1,jalandhar,jalandhar,Yes,Yes,0.00,3.0,3,"Studio, 2 BHK, 3BHK",< $400,...,0,0,0,0,0,0,0,0,1,0
506,0,surat,surat,Yes,Yes,0.00,3.0,2,"1BHK, 2 BHK",< $550,...,0,1,0,0,0,0,0,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,3.0,"2, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,1,0,0,0,1
508,1,mumbai,mumbai,Yes,Yes,3.00,3.0,4,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,1.0,I can stay in Hall too,2 BHK,< $550,...,0,0,0,0,0,1,0,0,0,1
510,0,chennai,boston,Yes,Yes,4.00,3.0,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
511,0,hosur,hosur,Yes,Yes,2.00,3.0,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,1
512,0,hyderabad,hyderabad,Yes,Yes,0.00,10.0,"1, 2","Studio, 1BHK, 2 BHK",< $450,...,0,0,0,0,0,0,0,0,0,0
513,0,chennai,chennai,Yes,No,5.00,3.0,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,1
514,0,indore,indore,Yes,Yes,0.00,3.0,"1, 2","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,3.0,2,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,5.0,"2, 3, 4","1BHK, 2 BHK, 3BHK",< $700,...,0,1,0,0,0,0,0,0,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,10.0,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,1
518,0,jaipur,jaipur,Yes,No,3.00,3.0,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,10.0,"1, 2","2 BHK, 3BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
520,0,raipur,raipur,Yes,Yes,2.00,5.0,"2, 3","1BHK, 2 BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
521,1,indore,indore,Yes,Yes,0.00,3.0,1,"Studio, 1BHK, 2 BHK",< $550,...,0,0,1,0,0,0,0,0,0,0

In [144]:
hall_ind in budd_new.person_per_room[0]

False

In [143]:
type(hall_ind)

str

In [132]:
pd.get_dummies(budd_new.person_per_room)

,1,2,3,4,"1, 2","1, 2, 3","1, 2, 3, 4","1, 2, 3, 4, I can stay in Hall too","1, 2, 3, I can stay in Hall too","1, 2, I can stay in Hall too",...,"2, 3, 4","2, 3, 4, I can stay in Hall too","2, 3, I can stay in Hall too","2, 4","2, 4, I can stay in Hall too","2, I can stay in Hall too","3, 4","3, 4, I can stay in Hall too","4, I can stay in Hall too",I can stay in Hall too
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
20,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
27,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
493,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
494,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
495,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
498,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
500,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
501,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
502,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
503,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
504,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
505,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
507,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
508,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
509,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
510,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
511,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
512,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
513,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
514,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
515,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
516,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
517,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
518,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
519,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
520,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
521,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [128]:
one_hot_course

,MS Biotechnology,MS Civil Engineering,MS Computer Science,MS Computer Systems Engineering,MS Data Science,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,1,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,1
11,0,0,1,0,0,0,0,0,0,0,0,0,0,0
12,0,1,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,1,0,0,0,0,0,0
14,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15,0,0,1,0,0,0,0,0,0,0,0,0,0,0
16,0,0,1,0,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,1,0,0,0,0,0,0,0,0
18,0,0,1,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,1,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,1,0,0,0,0,0,0
21,0,0,1,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,1,0,0,0
23,0,0,1,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,1,0,0,0,0,0,0
25,0,0,1,0,0,0,0,0,0,0,0,0,0,0
26,0,0,1,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,1,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,1,0,0,0,0
29,0,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,0,0,0,0,0,0,0,1,0,0,0,0,0,0
494,0,0,1,0,0,0,0,0,0,0,0,0,0,0
495,0,0,0,0,0,0,0,0,0,0,1,0,0,0
496,0,0,0,0,0,0,0,0,1,0,0,0,0,0
497,0,0,0,0,0,0,0,1,0,0,0,0,0,0
498,0,0,0,1,0,0,0,0,0,0,0,0,0,0
499,0,0,1,0,0,0,0,0,0,0,0,0,0,0
500,0,0,1,0,0,0,0,0,0,0,0,0,0,0
501,0,0,0,0,0,0,0,0,0,0,1,0,0,0
502,0,0,0,0,0,0,0,0,1,0,0,0,0,0
503,0,0,1,0,0,0,0,0,0,0,0,0,0,0
504,0,0,0,0,0,0,0,0,0,0,0,1,0,0
505,0,0,0,0,0,0,0,0,0,0,0,0,0,1
506,0,0,0,0,0,0,1,0,0,0,0,0,0,0
507,0,0,0,0,0,0,0,0,0,0,1,0,0,0
508,0,0,0,0,0,0,0,0,0,0,1,0,0,0
509,0,0,0,0,0,0,0,0,0,0,1,0,0,0
510,0,0,0,0,0,0,0,1,0,0,0,0,0,0
511,0,0,1,0,0,0,0,0,0,0,0,0,0,0
512,0,0,0,1,0,0,0,0,0,0,0,0,0,0
513,0,0,1,0,0,0,0,0,0,0,0,0,0,0
514,0,0,1,0,0,0,0,0,0,0,0,0,0,0
515,0,0,0,1,0,0,0,0,0,0,0,0,0,0
516,0,0,0,0,0,0,1,0,0,0,0,0,0,0
517,0,0,1,0,0,0,0,0,0,0,0,0,0,0
518,0,0,1,0,0,0,0,0,0,0,0,0,0,0
519,0,0,0,0,0,0,0,0,0,0,1,0,0,0
520,0,0,0,0,0,0,0,0,0,0,1,0,0,0
521,0,0,0,0,0,0,0,1,0,0,0,0,0,0
522,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [159]:
budd_new.to_csv('budd_new.csv')

# Start new here with semi-cleaned CSV

In [12]:
budd_new = pd.read_csv('budd_new.csv', index_col=0)

In [13]:
budd_new

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,person_per_room,apt_type,rent_budget,...,MS Electrical and Computer Engineering,MS Energy Systems,MS Engineering Management,MS Industrial Engineering,MS Information Assurance and Cyber Security,MS Information Systems,MS Mechanical Engineering,MS Project Management,Others,hall_yes_no
0,0,mumbai,mumbai,Yes,Yes,3.50,3.0,"1, 2, 3","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,3.0,"1, 2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,1.80,3.0,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,5.0,"2, 3, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,1
4,0,chennai,chennai,No,Yes,2.00,10.0,"2, 3","Studio, 1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
5,1,mangalore,pune,Yes,Yes,2.80,3.0,1,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,10.0,"1, 2","Studio, 1BHK, 2 BHK",< $400,...,0,0,1,0,0,0,0,0,0,0
7,1,indore,mumbai,Yes,Yes,3.50,5.0,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,0,0,0,0,0,0,0
8,0,bangalore,chennai,Yes,Yes,0.60,3.0,"4, I can stay in Hall too",2 BHK,< $500,...,0,0,1,0,0,0,0,0,0,1
9,0,pune,pune,Yes,Yes,2.50,3.0,"3, 4","2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
10,0,bangalore,mumbai,Yes,Yes,2.50,1.0,2,2 BHK,< $550,...,0,0,0,0,0,0,0,0,1,0
11,0,hyderabad,hyderabad,Yes,Yes,0.80,10.0,"1, 2, 3","2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,3.0,1,2 BHK,< $550,...,0,0,0,0,0,0,0,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,5.0,"2, 3","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,1,0,0,0,0,0,0,0
14,1,d,h,Yes,Yes,5.00,1.0,2,Studio,< $500,...,0,0,0,0,0,0,0,0,0,0
15,1,pune,pune,Yes,Yes,0.00,3.0,2,"Studio, 1BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
16,0,chennai,chennai,Yes,Yes,3.50,5.0,"1, 2, 3, 4","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,3.0,1,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,1,0,0,0,0,0,0,0,0,0
18,0,nagpur,nagpur,Yes,Yes,0.00,5.0,"1, 2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,1
19,0,vadodara,vadodara,Yes,Yes,0.30,3.0,"2, 4",2 BHK,< $550,...,0,1,0,0,0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,3.0,2,"2 BHK, 3BHK",< $450,...,0,0,1,0,0,0,0,0,0,0
21,0,kochi,kochi,Yes,Yes,1.80,5.0,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
22,0,mumbai,mumbai,Yes,Yes,0.00,5.0,"1, 2","Studio, 1BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
23,0,bangalore,bangalore,Yes,Yes,2.00,5.0,"3, 4","Studio, 2 BHK, 3BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
24,0,mumbai,mumbai,Yes,Yes,0.40,3.0,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,1
25,0,sirsa,pune,Yes,Yes,2.20,5.0,2,"1BHK, 2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
26,0,pune,pune,Yes,Yes,0.00,5.0,"3, 4, I can stay in Hall too","1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,1
27,0,mumbai,mumbai,Yes,Yes,0.30,5.0,"1, 2","1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
28,0,pune,pune,Yes,Yes,0.00,5.0,"2, 3","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,...,0,0,0,0,1,0,0,0,0,0
29,0,lucknow,raipur,Yes,No,0.00,5.0,"1, 2, 3, 4","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,5.0,"3, 4","1BHK, 2 BHK",< $550,...,0,0,0,0,1,0,0,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,3.0,"1, 2",2 BHK,< $500,...,0,0,1,0,0,0,0,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,3.0,"1, 2, 3","1BHK, 2 BHK, 3BHK",< $700,...,0,0,0,0,0,0,0,0,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,3.0,1,"2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,1,0,0,0,0
496,0,up,mumbai,Yes,Yes,0.40,1.0,1,"2 BHK, 3BHK, 4 BHK",< $1000,...,0,0,0,1,0,0,0,0,0,0
497,0,mumbai,mumbai,Yes,Yes,1.00,5.0,"3, 4","1BHK, 2 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,1.0,"1, 2","Studio, 1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
499,0,dehradun,dehradun,Yes,Yes,1.00,1.0,1,1BHK,< $500,...,0,0,0,0,0,0,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,3.0,2,"1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,1.0,4,2 BHK,< $500,...,0,0,0,0,0,1,0,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,10.0,2,"2 BHK, 3BHK",< $500,...,0,0,0,1,0,0,0,0,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,3.0,"1, 2","2 BHK, 3BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
504,0,mehsana,surat,Yes,Yes,0.00,5.0,"1, 2, 3, 4, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,0,1,0,0,1
505,1,jalandhar,jalandhar,Yes,Yes,0.00,3.0,3,"Studio, 2 BHK, 3BHK",< $400,...,0,0,0,0,0,0,0,0,1,0
506,0,surat,surat,Yes,Yes,0.00,3.0,2,"1BHK, 2 BHK",< $550,...,0,1,0,0,0,0,0,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,3.0,"2, I can stay in Hall too",2 BHK,< $550,...,0,0,0,0,0,1,0,0,0,1
508,1,mumbai,mumbai,Yes,Yes,3.00,3.0,4,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,1.0,I can stay in Hall too,2 BHK,< $550,...,0,0,0,0,0,1,0,0,0,1
510,0,chennai,boston,Yes,Yes,4.00,3.0,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,1,0,0,0,0,0,0,0
511,0,hosur,hosur,Yes,Yes,2.00,3.0,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,1
512,0,hyderabad,hyderabad,Yes,Yes,0.00,10.0,"1, 2","Studio, 1BHK, 2 BHK",< $450,...,0,0,0,0,0,0,0,0,0,0
513,0,chennai,chennai,Yes,No,5.00,3.0,"1, 2, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,1
514,0,indore,indore,Yes,Yes,0.00,3.0,"1, 2","1BHK, 2 BHK",< $550,...,0,0,0,0,0,0,0,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,3.0,2,"1BHK, 2 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,5.0,"2, 3, 4","1BHK, 2 BHK, 3BHK",< $700,...,0,1,0,0,0,0,0,0,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,10.0,"2, 3, 4, I can stay in Hall too","Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,...,0,0,0,0,0,0,0,0,0,1
518,0,jaipur,jaipur,Yes,No,3.00,3.0,2,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,...,0,0,0,0,0,0,0,0,0,0
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,10.0,"1, 2","2 BHK, 3BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
520,0,raipur,raipur,Yes,Yes,2.00,5.0,"2, 3","1BHK, 2 BHK",< $500,...,0,0,0,0,0,1,0,0,0,0
521,1,indore,indore,Yes,Yes,0.00,3.0,1,"Studio, 1BHK, 2 BHK",< $550,...,0,0,1,0,0,0,0,0,0,0

In [14]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
person_per_room                                  9
apt_type                                         9
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
dtype: int64

In [20]:
[str(d).split(',')[-2] if hall_ind in str(d) else str(d).split(',')[-1] for (d) in budd_new.person_per_room]

IndexError: list index out of range

In [36]:
[(','.join(str(d).split(',') +str(0))) if hall_ind in str(d) else d for d in budd_new.person_per_room]

TypeError: can only concatenate list (not "str") to list

In [38]:
budd_new.person_per_room

0                                 1, 2, 3
1                                 1, 2, 3
2                                       2
3            2, 3, I can stay in Hall too
4                                    2, 3
5                                       1
6                                    1, 2
7                                       1
8               4, I can stay in Hall too
9                                    3, 4
10                                      2
11                                1, 2, 3
12                                      1
13                                   2, 3
14                                      2
15                                      2
16                             1, 2, 3, 4
17                                      1
18     1, 2, 3, 4, I can stay in Hall too
19                                   2, 4
20                                      2
21                                   1, 2
22                                   1, 2
23                                   3, 4
24        2, 3, 4, I can stay in Hall too
25                                      2
26           3, 4, I can stay in Hall too
27                                   1, 2
28                                   2, 3
29                             1, 2, 3, 4
                      ...
492                                  3, 4
493                                  1, 2
494                               1, 2, 3
495                                     1
496                                     1
497                                  3, 4
498                                  1, 2
499                                     1
500                                     2
501                                     4
502                                     2
503                                  1, 2
504    1, 2, 3, 4, I can stay in Hall too
505                                     3
506                                     2
507             2, I can stay in Hall too
508                                     4
509                I can stay in Hall too
510                                     2
511          1, 2, I can stay in Hall too
512                                  1, 2
513          1, 2, I can stay in Hall too
514                                  1, 2
515                                     2
516                               2, 3, 4
517       2, 3, 4, I can stay in Hall too
518                                     2
519                                  1, 2
520                                  2, 3
521                                     1
Name: person_per_room, Length: 522, dtype: object

In [39]:
d = [4,5,6,7,8,9]

In [42]:
del(d[0])

In [43]:
d

[5, 6, 7, 8, 9]

In [47]:
for ind, i in enumerate(budd_new.person_per_room):
    if len(str(i).split(',')) == 1 and hall_ind in str(i):
        print(ind, i)
        budd_new.set_value(ind, 'person_per_room', 2)

87 I can stay in Hall too
145 I can stay in Hall too
346 I can stay in Hall too
370 I can stay in Hall too
399 I can stay in Hall too
509 I can stay in Hall too

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.

In [59]:
nansss = 0
max_ppr = []
for d in budd_new.person_per_room:
    try:    
        if hall_ind in str(d):
            new_d = str(d).split(',')
            del(new_d[-1])
            max_per_room = (max(int(j) for j in new_d))

        else:
            max_per_room = (max(int(j) for j in str(d).split(',')))
#         print(max_per_room)
        max_ppr.append(max_per_room)
        
    except:
        nansss += 1
        max_ppr.append(d)
#         print(d)
print('NAN COUNT:', nansss)
print('Length of ppr:', len(max_ppr))

NAN COUNT: 9
Length of ppr: 522

In [60]:
budd_new['max_ppr'] = max_ppr

In [63]:
budd_new = budd_new.drop(labels=['person_per_room'], axis = 1)

In [67]:
budd_new.max_ppr = budd_new.max_ppr.fillna(np.average(budd_new.max_ppr[budd_new.max_ppr.notnull()]))

In [69]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         9
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
dtype: int64

In [86]:
budd_new.apt_type = budd_new.apt_type.fillna('Studio, 1BHK, 2 BHK, 3BHK, 4 BHK')

In [87]:
apt_types = ['1BHK', '2 BHK', '3BHK', '4 BHK', 'Studio']
for a in apt_types:
    budd_new[a] = [0]*len(budd_new)

In [88]:
budd_new

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,apt_type,rent_budget,alcohol,...,MS Mechanical Engineering,MS Project Management,Others,hall_yes_no,max_ppr,1BHK,2 BHK,3BHK,4 BHK,Studio
0,0,mumbai,mumbai,Yes,Yes,3.50,3.0,"1BHK, 2 BHK",< $550,Strictly NO,...,0,0,0,0,3.0,0,0,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,3.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,0,3.0,0,0,0,0,0
2,1,davanagere,bangalore,Yes,Yes,1.80,3.0,"1BHK, 2 BHK, 3BHK",< $550,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,1,3.0,0,0,0,0,0
4,0,chennai,chennai,No,Yes,2.00,10.0,"Studio, 1BHK, 2 BHK, 3BHK",< $700,Flexible,...,0,0,0,0,3.0,0,0,0,0,0
5,1,mangalore,pune,Yes,Yes,2.80,3.0,"1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,10.0,"Studio, 1BHK, 2 BHK",< $400,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
7,1,indore,mumbai,Yes,Yes,3.50,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
8,0,bangalore,chennai,Yes,Yes,0.60,3.0,2 BHK,< $500,Flexible,...,0,0,0,1,4.0,0,0,0,0,0
9,0,pune,pune,Yes,Yes,2.50,3.0,"2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
10,0,bangalore,mumbai,Yes,Yes,2.50,1.0,2 BHK,< $550,Flexible,...,0,0,1,0,2.0,0,0,0,0,0
11,0,hyderabad,hyderabad,Yes,Yes,0.80,10.0,"2 BHK, 3BHK",< $500,Flexible,...,0,0,0,0,3.0,0,0,0,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,3.0,2 BHK,< $550,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,0,3.0,0,0,0,0,0
14,1,d,h,Yes,Yes,5.00,1.0,Studio,< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
15,1,pune,pune,Yes,Yes,0.00,3.0,"Studio, 1BHK",< $550,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
16,0,chennai,chennai,Yes,Yes,3.50,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
18,0,nagpur,nagpur,Yes,Yes,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,1,4.0,0,0,0,0,0
19,0,vadodara,vadodara,Yes,Yes,0.30,3.0,2 BHK,< $550,Strictly NO,...,0,0,0,0,4.0,0,0,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,3.0,"2 BHK, 3BHK",< $450,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
21,0,kochi,kochi,Yes,Yes,1.80,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
22,0,mumbai,mumbai,Yes,Yes,0.00,5.0,"Studio, 1BHK",< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
23,0,bangalore,bangalore,Yes,Yes,2.00,5.0,"Studio, 2 BHK, 3BHK",< $500,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
24,0,mumbai,mumbai,Yes,Yes,0.40,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Strictly Yes,...,0,0,0,1,4.0,0,0,0,0,0
25,0,sirsa,pune,Yes,Yes,2.20,5.0,"1BHK, 2 BHK, 3BHK",< $550,Strictly Yes,...,0,0,0,0,2.0,0,0,0,0,0
26,0,pune,pune,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,1,4.0,0,0,0,0,0
27,0,mumbai,mumbai,Yes,Yes,0.30,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
28,0,pune,pune,Yes,Yes,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Strictly Yes,...,0,0,0,0,3.0,0,0,0,0,0
29,0,lucknow,raipur,Yes,No,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Strictly NO,...,0,0,0,0,4.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,5.0,"1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,3.0,2 BHK,< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,3.0,"1BHK, 2 BHK, 3BHK",< $700,Strictly NO,...,0,0,0,0,3.0,0,0,0,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,3.0,"2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
496,0,up,mumbai,Yes,Yes,0.40,1.0,"2 BHK, 3BHK, 4 BHK",< $1000,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
497,0,mumbai,mumbai,Yes,Yes,1.00,5.0,"1BHK, 2 BHK",< $500,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,1.0,"Studio, 1BHK, 2 BHK",< $500,Strictly NO,...,0,0,0,0,2.0,0,0,0,0,0
499,0,dehradun,dehradun,Yes,Yes,1.00,1.0,1BHK,< $500,Flexible,...,0,0,0,0,1.0,0,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",< $550,Strictly NO,...,0,0,0,0,2.0,0,0,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,1.0,2 BHK,< $500,Strictly NO,...,0,0,0,0,4.0,0,0,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,10.0,"2 BHK, 3BHK",< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,3.0,"2 BHK, 3BHK",< $550,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
504,0,mehsana,surat,Yes,Yes,0.00,5.0,2 BHK,< $550,Flexible,...,1,0,0,1,4.0,0,0,0,0,0
505,1,jalandhar,jalandhar,Yes,Yes,0.00,3.0,"Studio, 2 BHK, 3BHK",< $400,Flexible,...,0,0,1,0,3.0,0,0,0,0,0
506,0,surat,surat,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,3.0,2 BHK,< $550,Flexible,...,0,0,0,1,2.0,0,0,0,0,0
508,1,mumbai,mumbai,Yes,Yes,3.00,3.0,"1BHK, 2 BHK",< $500,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,1.0,2 BHK,< $550,Flexible,...,0,0,0,1,2.0,0,0,0,0,0
510,0,chennai,boston,Yes,Yes,4.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
511,0,hosur,hosur,Yes,Yes,2.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,1,2.0,0,0,0,0,0
512,0,hyderabad,hyderabad,Yes,Yes,0.00,10.0,"Studio, 1BHK, 2 BHK",< $450,Strictly NO,...,0,0,0,0,2.0,0,0,0,0,0
513,0,chennai,chennai,Yes,No,5.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,1,2.0,0,0,0,0,0
514,0,indore,indore,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",< $550,Strictly NO,...,0,0,0,0,2.0,0,0,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,3.0,"1BHK, 2 BHK",< $500,Strictly NO,...,0,0,0,0,2.0,0,0,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK",< $700,Flexible,...,0,0,0,0,4.0,0,0,0,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,10.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,1,4.0,0,0,0,0,0
518,0,jaipur,jaipur,Yes,No,3.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,0
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,10.0,"2 BHK, 3BHK",< $500,Strictly Yes,...,0,0,0,0,2.0,0,0,0,0,0
520,0,raipur,raipur,Yes,Yes,2.00,5.0,"1BHK, 2 BHK",< $500,Strictly NO,...,0,0,0,0,3.0,0,0,0,0,0
521,1,indore,indore,Yes,Yes,0.00,3.0,"Studio, 1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,1.0,0,0,0,0,0

In [89]:
for ind, apt_choice in enumerate(budd_new.apt_type):
# try:
    for at in apt_types:
        if at in str(apt_choice):
            budd_new.set_value(ind, at, 1)
#     except:
#         print(apt_choice)

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """

In [92]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

In [93]:
budd_new.to_csv('budd_new.csv')

# Restart on 20/6

In [47]:
budd_new = pd.read_csv('budd_new.csv', index_col = 0)

In [48]:
budd_new

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,apt_type,rent_budget,alcohol,...,MS Mechanical Engineering,MS Project Management,Others,hall_yes_no,max_ppr,1BHK,2 BHK,3BHK,4 BHK,Studio
0,0,mumbai,mumbai,Yes,Yes,3.50,3.0,"1BHK, 2 BHK",< $550,Strictly NO,...,0,0,0,0,3.0,1,1,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,3.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,0,3.0,1,1,1,1,0
2,1,davanagere,bangalore,Yes,Yes,1.80,3.0,"1BHK, 2 BHK, 3BHK",< $550,Flexible,...,0,0,0,0,2.0,1,1,1,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,1,3.0,1,1,1,1,0
4,0,chennai,chennai,No,Yes,2.00,10.0,"Studio, 1BHK, 2 BHK, 3BHK",< $700,Flexible,...,0,0,0,0,3.0,1,1,1,0,1
5,1,mangalore,pune,Yes,Yes,2.80,3.0,"1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,1.0,1,1,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,10.0,"Studio, 1BHK, 2 BHK",< $400,Flexible,...,0,0,0,0,2.0,1,1,0,0,1
7,1,indore,mumbai,Yes,Yes,3.50,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $1000,Flexible,...,0,0,0,0,1.0,1,1,1,1,1
8,0,bangalore,chennai,Yes,Yes,0.60,3.0,2 BHK,< $500,Flexible,...,0,0,0,1,4.0,0,1,0,0,0
9,0,pune,pune,Yes,Yes,2.50,3.0,"2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,4.0,0,1,1,1,0
10,0,bangalore,mumbai,Yes,Yes,2.50,1.0,2 BHK,< $550,Flexible,...,0,0,1,0,2.0,0,1,0,0,0
11,0,hyderabad,hyderabad,Yes,Yes,0.80,10.0,"2 BHK, 3BHK",< $500,Flexible,...,0,0,0,0,3.0,0,1,1,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,3.0,2 BHK,< $550,Flexible,...,0,0,0,0,1.0,0,1,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,0,3.0,1,1,1,1,0
14,1,d,h,Yes,Yes,5.00,1.0,Studio,< $500,Flexible,...,0,0,0,0,2.0,0,0,0,0,1
15,1,pune,pune,Yes,Yes,0.00,3.0,"Studio, 1BHK",< $550,Flexible,...,0,0,0,0,2.0,1,0,0,0,1
16,0,chennai,chennai,Yes,Yes,3.50,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,4.0,1,1,1,1,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,0,1.0,1,1,1,1,1
18,0,nagpur,nagpur,Yes,Yes,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,1,4.0,1,1,1,1,1
19,0,vadodara,vadodara,Yes,Yes,0.30,3.0,2 BHK,< $550,Strictly NO,...,0,0,0,0,4.0,0,1,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,3.0,"2 BHK, 3BHK",< $450,Flexible,...,0,0,0,0,2.0,0,1,1,0,0
21,0,kochi,kochi,Yes,Yes,1.80,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Flexible,...,0,0,0,0,2.0,1,1,1,1,0
22,0,mumbai,mumbai,Yes,Yes,0.00,5.0,"Studio, 1BHK",< $500,Flexible,...,0,0,0,0,2.0,1,0,0,0,1
23,0,bangalore,bangalore,Yes,Yes,2.00,5.0,"Studio, 2 BHK, 3BHK",< $500,Flexible,...,0,0,0,0,4.0,0,1,1,0,1
24,0,mumbai,mumbai,Yes,Yes,0.40,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Strictly Yes,...,0,0,0,1,4.0,1,1,1,1,1
25,0,sirsa,pune,Yes,Yes,2.20,5.0,"1BHK, 2 BHK, 3BHK",< $550,Strictly Yes,...,0,0,0,0,2.0,1,1,1,0,0
26,0,pune,pune,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,1,4.0,1,1,1,1,0
27,0,mumbai,mumbai,Yes,Yes,0.30,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,2.0,1,1,1,1,0
28,0,pune,pune,Yes,Yes,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $700,Strictly Yes,...,0,0,0,0,3.0,1,1,1,1,1
29,0,lucknow,raipur,Yes,No,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Strictly NO,...,0,0,0,0,4.0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,5.0,"1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,4.0,1,1,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,3.0,2 BHK,< $500,Flexible,...,0,0,0,0,2.0,0,1,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,3.0,"1BHK, 2 BHK, 3BHK",< $700,Strictly NO,...,0,0,0,0,3.0,1,1,1,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,3.0,"2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,0,1.0,0,1,1,1,0
496,0,up,mumbai,Yes,Yes,0.40,1.0,"2 BHK, 3BHK, 4 BHK",< $1000,Flexible,...,0,0,0,0,1.0,0,1,1,1,0
497,0,mumbai,mumbai,Yes,Yes,1.00,5.0,"1BHK, 2 BHK",< $500,Flexible,...,0,0,0,0,4.0,1,1,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,1.0,"Studio, 1BHK, 2 BHK",< $500,Strictly NO,...,0,0,0,0,2.0,1,1,0,0,1
499,0,dehradun,dehradun,Yes,Yes,1.00,1.0,1BHK,< $500,Flexible,...,0,0,0,0,1.0,1,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",< $550,Strictly NO,...,0,0,0,0,2.0,1,1,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,1.0,2 BHK,< $500,Strictly NO,...,0,0,0,0,4.0,0,1,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,10.0,"2 BHK, 3BHK",< $500,Flexible,...,0,0,0,0,2.0,0,1,1,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,3.0,"2 BHK, 3BHK",< $550,Flexible,...,0,0,0,0,2.0,0,1,1,0,0
504,0,mehsana,surat,Yes,Yes,0.00,5.0,2 BHK,< $550,Flexible,...,1,0,0,1,4.0,0,1,0,0,0
505,1,jalandhar,jalandhar,Yes,Yes,0.00,3.0,"Studio, 2 BHK, 3BHK",< $400,Flexible,...,0,0,1,0,3.0,0,1,1,0,1
506,0,surat,surat,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,2.0,1,1,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,3.0,2 BHK,< $550,Flexible,...,0,0,0,1,2.0,0,1,0,0,0
508,1,mumbai,mumbai,Yes,Yes,3.00,3.0,"1BHK, 2 BHK",< $500,Flexible,...,0,0,0,0,4.0,1,1,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,1.0,2 BHK,< $550,Flexible,...,0,0,0,1,2.0,0,1,0,0,0
510,0,chennai,boston,Yes,Yes,4.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,2.0,1,1,1,1,1
511,0,hosur,hosur,Yes,Yes,2.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,1,2.0,1,1,1,1,1
512,0,hyderabad,hyderabad,Yes,Yes,0.00,10.0,"Studio, 1BHK, 2 BHK",< $450,Strictly NO,...,0,0,0,0,2.0,1,1,0,0,1
513,0,chennai,chennai,Yes,No,5.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,1,2.0,1,1,1,1,1
514,0,indore,indore,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",< $550,Strictly NO,...,0,0,0,0,2.0,1,1,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,3.0,"1BHK, 2 BHK",< $500,Strictly NO,...,0,0,0,0,2.0,1,1,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK",< $700,Flexible,...,0,0,0,0,4.0,1,1,1,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,10.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $550,Flexible,...,0,0,0,1,4.0,1,1,1,1,1
518,0,jaipur,jaipur,Yes,No,3.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",< $500,Flexible,...,0,0,0,0,2.0,1,1,1,1,1
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,10.0,"2 BHK, 3BHK",< $500,Strictly Yes,...,0,0,0,0,2.0,0,1,1,0,0
520,0,raipur,raipur,Yes,Yes,2.00,5.0,"1BHK, 2 BHK",< $500,Strictly NO,...,0,0,0,0,3.0,1,1,0,0,0
521,1,indore,indore,Yes,Yes,0.00,3.0,"Studio, 1BHK, 2 BHK",< $550,Flexible,...,0,0,0,0,1.0,1,1,0,0,1

In [49]:
budd_new.isnull().sum()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      9
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

### rent_budget cleaning

In [50]:
budd_new.rent_budget.value_counts()

< $500     165
< $550     134
< $700      84
< $450      79
< $400      34
< $1000     15
$1000 +      2
Name: rent_budget, dtype: int64

In [51]:
budd_new.rent_budget[budd_new.rent_budget == 0] = 1000

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [52]:
for ind, budget in enumerate(budd_new.rent_budget):
    try:
        budget = str(budget).strip()
        budd_new.set_value(ind, 'rent_budget', int(budget[3:]))
#         break
    except:
        continue

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.

In [53]:
def check_null():
    return(budd_new.isnull().sum())

In [54]:
budd_new.rent_budget = budd_new.rent_budget.fillna('< $500')

In [55]:
budd_new.rent_budget.value_counts()

500        165
550        134
700         84
450         79
400         34
1000        15
< $500       9
$1000 +      2
Name: rent_budget, dtype: int64

In [56]:
check_null()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      0
alcohol                                          9
smoking                                          9
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

In [57]:
budd_new.alcohol.value_counts()

Flexible        420
Strictly NO      70
Strictly Yes     23
Name: alcohol, dtype: int64

In [58]:
budd_new.alcohol = budd_new.alcohol.fillna('Flexible')

budd_new.alcohol = budd_new.alcohol.replace('Flexible', 0)
budd_new.alcohol = budd_new.alcohol.replace('Strictly NO', 1)
budd_new.alcohol = budd_new.alcohol.replace('Strictly Yes', 2)

In [59]:
budd_new.alcohol.value_counts()

0    429
1     70
2     23
Name: alcohol, dtype: int64

In [60]:
budd_new.smoking.value_counts()

Flexible        288
Strictly No     222
Strictly Yes      3
Name: smoking, dtype: int64

In [61]:
budd_new.smoking = budd_new.smoking.fillna('Flexible')

budd_new.smoking = budd_new.smoking.replace('Flexible', 0)
budd_new.smoking = budd_new.smoking.replace('Strictly No', 1)
budd_new.smoking = budd_new.smoking.replace('Strictly Yes', 2)

In [62]:
budd_new.smoking.value_counts()

0    297
1    222
2      3
Name: smoking, dtype: int64

In [63]:
check_null()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      0
alcohol                                          0
smoking                                          0
special_pref                                   369
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

In [64]:
budd_new = budd_new.drop(labels = ['special_pref'], axis = 1)

In [65]:
check_null()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      0
alcohol                                          0
smoking                                          0
food_pref                                        9
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

In [66]:
budd_new.food_pref.value_counts()

Flexible (I prefer  veg or Non -veg for myself but ready to live with anyone)    396
Strictly Veg                                                                      91
Strictly Non Veg                                                                  26
Name: food_pref, dtype: int64

In [67]:
budd_new.food_pref = budd_new.food_pref.fillna('Flexible (I prefer  veg or Non -veg for myself but ready to live with anyone)')

budd_new.food_pref = budd_new.food_pref.replace('Flexible (I prefer  veg or Non -veg for myself but ready to live with anyone)', 0)
budd_new.food_pref = budd_new.food_pref.replace('Strictly Veg', 1)
budd_new.food_pref = budd_new.food_pref.replace('Strictly Non Veg', 2)

In [68]:
budd_new.food_pref.value_counts()

0    405
1     91
2     26
Name: food_pref, dtype: int64

In [69]:
check_null()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      0
alcohol                                          0
smoking                                          0
food_pref                                        0
cul_skills                                      16
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

#### Cul skills

In [74]:
budd_new['cul_skills ']

0        Sometimes
1           Expert
2        Sometimes
3        Sometimes
4        Sometimes
5        Sometimes
6      Never tried
7        Sometimes
8        Sometimes
9        Sometimes
10       Sometimes
11       Sometimes
12       Sometimes
13       Sometimes
14       Sometimes
15       Sometimes
16       Sometimes
17       Sometimes
18       Sometimes
19       Sometimes
20       Sometimes
21       Sometimes
22       Sometimes
23          Expert
24       Sometimes
25       Sometimes
26       Sometimes
27          Expert
28       Sometimes
29       Sometimes
          ...
492      Sometimes
493      Sometimes
494         Expert
495      Sometimes
496         Expert
497      Sometimes
498      Sometimes
499      Sometimes
500      Sometimes
501      Sometimes
502      Sometimes
503      Sometimes
504      Sometimes
505      Sometimes
506      Sometimes
507      Sometimes
508      Sometimes
509      Sometimes
510      Sometimes
511         Expert
512      Sometimes
513      Sometimes
514      Sometimes
515      Sometimes
516    Never tried
517         Expert
518      Sometimes
519      Sometimes
520      Sometimes
521      Sometimes
Name: cul_skills , Length: 522, dtype: object

In [77]:
budd_new = budd_new.rename(columns={'cul_skills ': 'cul_skills'})

In [79]:
budd_new.cul_skills.value_counts()

Sometimes      415
Expert          60
Never tried     31
Name: cul_skills, dtype: int64

In [80]:
budd_new.cul_skills = budd_new.cul_skills.fillna('Sometimes')

budd_new.cul_skills = budd_new.cul_skills.replace('Sometimes', 0)
budd_new.cul_skills = budd_new.cul_skills.replace('Expert', 1)
budd_new.cul_skills = budd_new.cul_skills.replace('Never tried', 2)

In [81]:

budd_new.cul_skills.value_counts()

0    431
1     60
2     31
Name: cul_skills, dtype: int64

In [82]:
check_null()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      0
alcohol                                          0
smoking                                          0
food_pref                                        0
cul_skills                                       0
looking_for_roommate                            23
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

In [84]:
budd_new.looking_for_roommate.value_counts()

Who can cook sometimes         404
No culinary skills required     95
Name: looking_for_roommate, dtype: int64

In [85]:
budd_new.looking_for_roommate = budd_new.looking_for_roommate.fillna('Who can cook sometimes')

budd_new.looking_for_roommate = budd_new.looking_for_roommate.replace('Who can cook sometimes', 0)
budd_new.looking_for_roommate = budd_new.looking_for_roommate.replace('No culinary skills required', 1)

In [86]:
check_null()

gender                                           0
hometown                                         0
current_city                                     0
need_roommate                                    0
open_to_other_branch                             0
work_ex                                          0
dist_from_uni                                    0
apt_type                                         0
rent_budget                                      0
alcohol                                          0
smoking                                          0
food_pref                                        0
cul_skills                                       0
looking_for_roommate                             0
hobbies                                        247
MS Biotechnology                                 0
MS Civil Engineering                             0
MS Computer Science                              0
MS Computer Systems Engineering                  0
MS Data Science                                  0
MS Electrical and Computer Engineering           0
MS Energy Systems                                0
MS Engineering Management                        0
MS Industrial Engineering                        0
MS Information Assurance and Cyber Security      0
MS Information Systems                           0
MS Mechanical Engineering                        0
MS Project Management                            0
Others                                           0
hall_yes_no                                      0
max_ppr                                          0
1BHK                                             0
2 BHK                                            0
3BHK                                             0
4 BHK                                            0
Studio                                           0
dtype: int64

In [88]:
budd_new = budd_new.drop(labels = ['hobbies'], axis = 1)

In [90]:
check_null()

gender                                         0
hometown                                       0
current_city                                   0
need_roommate                                  0
open_to_other_branch                           0
work_ex                                        0
dist_from_uni                                  0
apt_type                                       0
rent_budget                                    0
alcohol                                        0
smoking                                        0
food_pref                                      0
cul_skills                                     0
looking_for_roommate                           0
MS Biotechnology                               0
MS Civil Engineering                           0
MS Computer Science                            0
MS Computer Systems Engineering                0
MS Data Science                                0
MS Electrical and Computer Engineering         0
MS Energy Systems                              0
MS Engineering Management                      0
MS Industrial Engineering                      0
MS Information Assurance and Cyber Security    0
MS Information Systems                         0
MS Mechanical Engineering                      0
MS Project Management                          0
Others                                         0
hall_yes_no                                    0
max_ppr                                        0
1BHK                                           0
2 BHK                                          0
3BHK                                           0
4 BHK                                          0
Studio                                         0
dtype: int64

In [91]:
budd_new

,gender,hometown,current_city,need_roommate,open_to_other_branch,work_ex,dist_from_uni,apt_type,rent_budget,alcohol,...,MS Mechanical Engineering,MS Project Management,Others,hall_yes_no,max_ppr,1BHK,2 BHK,3BHK,4 BHK,Studio
0,0,mumbai,mumbai,Yes,Yes,3.50,3.0,"1BHK, 2 BHK",550,1,...,0,0,0,0,3.0,1,1,0,0,0
1,0,patna,bangalore,Yes,Yes,3.50,3.0,"1BHK, 2 BHK, 3BHK, 4 BHK",550,0,...,0,0,0,0,3.0,1,1,1,1,0
2,1,davanagere,bangalore,Yes,Yes,1.80,3.0,"1BHK, 2 BHK, 3BHK",550,0,...,0,0,0,0,2.0,1,1,1,0,0
3,0,kolkata,kolkata,Yes,Yes,3.50,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,1,3.0,1,1,1,1,0
4,0,chennai,chennai,No,Yes,2.00,10.0,"Studio, 1BHK, 2 BHK, 3BHK",700,0,...,0,0,0,0,3.0,1,1,1,0,1
5,1,mangalore,pune,Yes,Yes,2.80,3.0,"1BHK, 2 BHK",550,0,...,0,0,0,0,1.0,1,1,0,0,0
6,0,nileshwar,bangalore,Yes,Yes,3.00,10.0,"Studio, 1BHK, 2 BHK",400,0,...,0,0,0,0,2.0,1,1,0,0,1
7,1,indore,mumbai,Yes,Yes,3.50,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",1000,0,...,0,0,0,0,1.0,1,1,1,1,1
8,0,bangalore,chennai,Yes,Yes,0.60,3.0,2 BHK,500,0,...,0,0,0,1,4.0,0,1,0,0,0
9,0,pune,pune,Yes,Yes,2.50,3.0,"2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,0,4.0,0,1,1,1,0
10,0,bangalore,mumbai,Yes,Yes,2.50,1.0,2 BHK,550,0,...,0,0,1,0,2.0,0,1,0,0,0
11,0,hyderabad,hyderabad,Yes,Yes,0.80,10.0,"2 BHK, 3BHK",500,0,...,0,0,0,0,3.0,0,1,1,0,0
12,0,bangalore,bangalore,Yes,Yes,0.00,3.0,2 BHK,550,0,...,0,0,0,0,1.0,0,1,0,0,0
13,0,amravati,nagpur,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",700,0,...,0,0,0,0,3.0,1,1,1,1,0
14,1,d,h,Yes,Yes,5.00,1.0,Studio,500,0,...,0,0,0,0,2.0,0,0,0,0,1
15,1,pune,pune,Yes,Yes,0.00,3.0,"Studio, 1BHK",550,0,...,0,0,0,0,2.0,1,0,0,0,1
16,0,chennai,chennai,Yes,Yes,3.50,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,0,4.0,1,1,1,1,0
17,0,mumbai,"wadala, mumbai",Yes,Yes,1.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",700,0,...,0,0,0,0,1.0,1,1,1,1,1
18,0,nagpur,nagpur,Yes,Yes,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",700,0,...,0,0,0,1,4.0,1,1,1,1,1
19,0,vadodara,vadodara,Yes,Yes,0.30,3.0,2 BHK,550,1,...,0,0,0,0,4.0,0,1,0,0,0
20,0,bangalore,bangalore,Yes,Yes,0.00,3.0,"2 BHK, 3BHK",450,0,...,0,0,0,0,2.0,0,1,1,0,0
21,0,kochi,kochi,Yes,Yes,1.80,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",700,0,...,0,0,0,0,2.0,1,1,1,1,0
22,0,mumbai,mumbai,Yes,Yes,0.00,5.0,"Studio, 1BHK",500,0,...,0,0,0,0,2.0,1,0,0,0,1
23,0,bangalore,bangalore,Yes,Yes,2.00,5.0,"Studio, 2 BHK, 3BHK",500,0,...,0,0,0,0,4.0,0,1,1,0,1
24,0,mumbai,mumbai,Yes,Yes,0.40,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",500,2,...,0,0,0,1,4.0,1,1,1,1,1
25,0,sirsa,pune,Yes,Yes,2.20,5.0,"1BHK, 2 BHK, 3BHK",550,2,...,0,0,0,0,2.0,1,1,1,0,0
26,0,pune,pune,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",550,0,...,0,0,0,1,4.0,1,1,1,1,0
27,0,mumbai,mumbai,Yes,Yes,0.30,5.0,"1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,0,2.0,1,1,1,1,0
28,0,pune,pune,Yes,Yes,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",700,2,...,0,0,0,0,3.0,1,1,1,1,1
29,0,lucknow,raipur,Yes,No,0.00,5.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",550,1,...,0,0,0,0,4.0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,pune,pune,Yes,Yes,4.00,5.0,"1BHK, 2 BHK",550,0,...,0,0,0,0,4.0,1,1,0,0,0
493,0,nagpur,nagpur,Yes,Yes,1.00,3.0,2 BHK,500,0,...,0,0,0,0,2.0,0,1,0,0,0
494,1,vadodara,vadodara,Yes,Yes,0.00,3.0,"1BHK, 2 BHK, 3BHK",700,1,...,0,0,0,0,3.0,1,1,1,0,0
495,0,mumbai,mumbai,Yes,Yes,0.00,3.0,"2 BHK, 3BHK, 4 BHK",550,0,...,0,0,0,0,1.0,0,1,1,1,0
496,0,up,mumbai,Yes,Yes,0.40,1.0,"2 BHK, 3BHK, 4 BHK",1000,0,...,0,0,0,0,1.0,0,1,1,1,0
497,0,mumbai,mumbai,Yes,Yes,1.00,5.0,"1BHK, 2 BHK",500,0,...,0,0,0,0,4.0,1,1,0,0,0
498,0,chennai,bangalore,Yes,Yes,1.08,1.0,"Studio, 1BHK, 2 BHK",500,1,...,0,0,0,0,2.0,1,1,0,0,1
499,0,dehradun,dehradun,Yes,Yes,1.00,1.0,1BHK,500,0,...,0,0,0,0,1.0,1,0,0,0,0
500,0,indore,indore,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",550,1,...,0,0,0,0,2.0,1,1,0,0,0
501,0,vadodara,vadodara,Yes,Yes,6.00,1.0,2 BHK,500,1,...,0,0,0,0,4.0,0,1,0,0,0
502,0,hyderabad,hyderabad,Yes,Yes,0.30,10.0,"2 BHK, 3BHK",500,0,...,0,0,0,0,2.0,0,1,1,0,0
503,0,himachal pradesh,delhi,Yes,Yes,1.00,3.0,"2 BHK, 3BHK",550,0,...,0,0,0,0,2.0,0,1,1,0,0
504,0,mehsana,surat,Yes,Yes,0.00,5.0,2 BHK,550,0,...,1,0,0,1,4.0,0,1,0,0,0
505,1,jalandhar,jalandhar,Yes,Yes,0.00,3.0,"Studio, 2 BHK, 3BHK",400,0,...,0,0,1,0,3.0,0,1,1,0,1
506,0,surat,surat,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",550,0,...,0,0,0,0,2.0,1,1,0,0,0
507,0,mumbai,mumbai,Yes,Yes,0.00,3.0,2 BHK,550,0,...,0,0,0,1,2.0,0,1,0,0,0
508,1,mumbai,mumbai,Yes,Yes,3.00,3.0,"1BHK, 2 BHK",500,0,...,0,0,0,0,4.0,1,1,0,0,0
509,0,indore,navi mumbai,Yes,Yes,3.00,1.0,2 BHK,550,0,...,0,0,0,1,2.0,0,1,0,0,0
510,0,chennai,boston,Yes,Yes,4.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,0,2.0,1,1,1,1,1
511,0,hosur,hosur,Yes,Yes,2.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,1,2.0,1,1,1,1,1
512,0,hyderabad,hyderabad,Yes,Yes,0.00,10.0,"Studio, 1BHK, 2 BHK",450,1,...,0,0,0,0,2.0,1,1,0,0,1
513,0,chennai,chennai,Yes,No,5.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,1,2.0,1,1,1,1,1
514,0,indore,indore,Yes,Yes,0.00,3.0,"1BHK, 2 BHK",550,1,...,0,0,0,0,2.0,1,1,0,0,0
515,0,thanjavur,thanjavur,Yes,Yes,1.00,3.0,"1BHK, 2 BHK",500,1,...,0,0,0,0,2.0,1,1,0,0,0
516,0,mangalore,india,Yes,Yes,0.00,5.0,"1BHK, 2 BHK, 3BHK",700,0,...,0,0,0,0,4.0,1,1,1,0,0
517,0,rajkot,mumbai,Yes,Yes,3.00,10.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",550,0,...,0,0,0,1,4.0,1,1,1,1,1
518,0,jaipur,jaipur,Yes,No,3.00,3.0,"Studio, 1BHK, 2 BHK, 3BHK, 4 BHK",500,0,...,0,0,0,0,2.0,1,1,1,1,1
519,0,navi mumbai,navi mumbai,Yes,Yes,4.00,10.0,"2 BHK, 3BHK",500,2,...,0,0,0,0,2.0,0,1,1,0,0
520,0,raipur,raipur,Yes,Yes,2.00,5.0,"1BHK, 2 BHK",500,1,...,0,0,0,0,3.0,1,1,0,0,0
521,1,indore,indore,Yes,Yes,0.00,3.0,"Studio, 1BHK, 2 BHK",550,0,...,0,0,0,0,1.0,1,1,0,0,1

In [92]:
budd_new.to_csv('budd_new.csv')

# 22nd June

In [37]:
budd_new = pd.read_csv('budd_new.csv', index_col = 0)

In [38]:
budd_new = budd_new.drop(labels = ['apt_type', 'hometown'], axis = 1)

In [39]:
budd_new.current_city.value_counts()

mumbai                  159
bangalore                84
pune                     50
chennai                  27
hyderabad                19
ahmedabad                14
nagpur                   11
vadodara                 10
indore                    9
delhi                     9
navi mumbai               8
thane                     7
india                     7
gurgaon                   5
bengaluru                 5
surat                     5
new delhi                 4
kolkata                   4
mysore                    3
dehradun                  3
goa                       3
coimbatore                2
bhopal                    2
jalgaon                   2
bangalore, karnataka      2
aurangabad                2
faridabad                 2
jaipur                    2
mumbai, india             2
noida                     2
                       ...
bhilai, durg              1
hubli                     1
satara                    1
sharjah, uae              1
bhubaneswar               1
thane,mumbai              1
banaglore                 1
bangalore, india          1
patras                    1
delhi ncr                 1
auranagabad               1
tiruchirappalli           1
east windsor              1
trichy                    1
boston                    1
pune, maharashtra         1
yelahanka                 1
h                         1
banglore                  1
chandigarh                1
sangli                    1
chennaia                  1
borivali                  1
nit waranagal             1
mumbai(bandra)            1
nigdi pune                1
meerut                    1
us                        1
sangli, mh                1
singapore                 1
Name: current_city, Length: 85, dtype: int64

In [40]:
all_cities = budd_new.current_city.unique()
num_cities = list(range(len(all_cities)))

In [41]:
city_num_dict = dict(zip(all_cities, num_cities))

In [42]:
city_num_dict

{'ahmedabad': 32,
 'ann arbor, michigan': 14,
 'auranagabad': 30,
 'aurangabad': 69,
 'banaglore': 41,
 'bangalore': 1,
 'bangalore, india': 66,
 'bangalore, karnataka': 42,
 'banglore': 79,
 'bengaluru': 22,
 'bhilai, durg': 64,
 'bhopal': 47,
 'bhubaneswar': 72,
 'borivali': 62,
 'boston': 82,
 'chandigarh': 48,
 'chennai': 3,
 'chennaia': 76,
 'coimbatore': 50,
 'dehradun': 17,
 'delhi': 16,
 'delhi ncr': 73,
 'dombivli': 57,
 'dubai': 59,
 'east windsor': 61,
 'faridabad': 43,
 'faridabad(ncr)': 44,
 'goa': 12,
 'guntur': 52,
 'gurgaon': 13,
 'h': 7,
 'hosur': 83,
 'hubli': 75,
 'hyderabad': 5,
 'india': 34,
 'indore': 51,
 'jaipur': 27,
 'jalandhar': 81,
 'jalgaon': 29,
 'kalyan': 60,
 'kerala': 67,
 'kochi': 10,
 'kolkata': 2,
 'mangalore': 26,
 'meerut': 20,
 'miraj': 46,
 'mumbai': 0,
 'mumbai(bandra)': 40,
 'mumbai, india': 58,
 'mysore': 19,
 'nagpur': 6,
 'navi mumbai': 23,
 'navi mumbai (panvel)': 25,
 'nellore': 31,
 'new delhi': 55,
 'nigdi pune': 54,
 'nit waranagal': 56,
 'noida': 49,
 'patras': 45,
 'pune': 4,
 'pune, maharashtra': 21,
 'raipur': 11,
 'sangli': 78,
 'sangli, mh': 33,
 'satara': 35,
 'sharjah, uae': 39,
 'singapore': 77,
 'solapur': 71,
 'surat': 18,
 'surendranagar': 68,
 'thane': 36,
 'thane(mumbai)': 65,
 'thane,mumbai': 53,
 'thanjavur': 84,
 'tiruchirappalli': 63,
 'trichy': 70,
 'us': 74,
 'vadodara': 9,
 'vapi': 37,
 'vellore': 28,
 'vidhya nagar': 38,
 'vijayawada': 15,
 'wadala, mumbai': 8,
 'yelahanka': 24,
 'zz': 80}

In [43]:
budd_new['current_city'] = budd_new['current_city'].map(city_num_dict)

In [44]:
budd_new = budd_new.drop(labels = ['need_roommate'], axis = 1)

In [48]:
budd_new.open_to_other_branch = budd_new.open_to_other_branch.replace('Yes', 0)
budd_new.open_to_other_branch = budd_new.open_to_other_branch.replace('No', 1)

In [50]:
budd_new.isnull().sum()

gender                                         0
current_city                                   0
open_to_other_branch                           0
work_ex                                        0
dist_from_uni                                  0
rent_budget                                    0
alcohol                                        0
smoking                                        0
food_pref                                      0
cul_skills                                     0
looking_for_roommate                           0
MS Biotechnology                               0
MS Civil Engineering                           0
MS Computer Science                            0
MS Computer Systems Engineering                0
MS Data Science                                0
MS Electrical and Computer Engineering         0
MS Energy Systems                              0
MS Engineering Management                      0
MS Industrial Engineering                      0
MS Information Assurance and Cyber Security    0
MS Information Systems                         0
MS Mechanical Engineering                      0
MS Project Management                          0
Others                                         0
hall_yes_no                                    0
max_ppr                                        0
1BHK                                           0
2 BHK                                          0
3BHK                                           0
4 BHK                                          0
Studio                                         0
dtype: int64

In [53]:
budd_new = budd_new.rename(columns = {'1BHK':'bhk_1', '2 BHK':'bhk_2', '3BHK':'bhk_3', '4 BHK':'bhk_4', 'Studio':'studio'})

In [54]:
 budd_new

,gender,current_city,open_to_other_branch,work_ex,dist_from_uni,rent_budget,alcohol,smoking,food_pref,cul_skills,...,MS Mechanical Engineering,MS Project Management,Others,hall_yes_no,max_ppr,bhk_1,bhk_2,bhk_3,bhk_4,studio
0,0,0,0,3.50,3.0,550,1,1,0,0,...,0,0,0,0,3.0,1,1,0,0,0
1,0,1,0,3.50,3.0,550,0,0,0,1,...,0,0,0,0,3.0,1,1,1,1,0
2,1,1,0,1.80,3.0,550,0,1,0,0,...,0,0,0,0,2.0,1,1,1,0,0
3,0,2,0,3.50,5.0,500,0,0,0,0,...,0,0,0,1,3.0,1,1,1,1,0
4,0,3,0,2.00,10.0,700,0,1,1,0,...,0,0,0,0,3.0,1,1,1,0,1
5,1,4,0,2.80,3.0,550,0,0,0,0,...,0,0,0,0,1.0,1,1,0,0,0
6,0,1,0,3.00,10.0,400,0,0,0,2,...,0,0,0,0,2.0,1,1,0,0,1
7,1,0,0,3.50,5.0,1000,0,1,1,0,...,0,0,0,0,1.0,1,1,1,1,1
8,0,3,0,0.60,3.0,500,0,0,0,0,...,0,0,0,1,4.0,0,1,0,0,0
9,0,4,0,2.50,3.0,500,0,0,0,0,...,0,0,0,0,4.0,0,1,1,1,0
10,0,0,0,2.50,1.0,550,0,1,1,0,...,0,0,1,0,2.0,0,1,0,0,0
11,0,5,0,0.80,10.0,500,0,1,0,0,...,0,0,0,0,3.0,0,1,1,0,0
12,0,1,0,0.00,3.0,550,0,0,0,0,...,0,0,0,0,1.0,0,1,0,0,0
13,0,6,0,0.00,5.0,700,0,0,0,0,...,0,0,0,0,3.0,1,1,1,1,0
14,1,7,0,5.00,1.0,500,0,0,2,0,...,0,0,0,0,2.0,0,0,0,0,1
15,1,4,0,0.00,3.0,550,0,1,0,0,...,0,0,0,0,2.0,1,0,0,0,1
16,0,3,0,3.50,5.0,500,0,0,0,0,...,0,0,0,0,4.0,1,1,1,1,0
17,0,8,0,1.00,3.0,700,0,1,0,0,...,0,0,0,0,1.0,1,1,1,1,1
18,0,6,0,0.00,5.0,700,0,1,0,0,...,0,0,0,1,4.0,1,1,1,1,1
19,0,9,0,0.30,3.0,550,1,1,0,0,...,0,0,0,0,4.0,0,1,0,0,0
20,0,1,0,0.00,3.0,450,0,1,1,0,...,0,0,0,0,2.0,0,1,1,0,0
21,0,10,0,1.80,5.0,700,0,0,0,0,...,0,0,0,0,2.0,1,1,1,1,0
22,0,0,0,0.00,5.0,500,0,1,0,0,...,0,0,0,0,2.0,1,0,0,0,1
23,0,1,0,2.00,5.0,500,0,0,0,1,...,0,0,0,0,4.0,0,1,1,0,1
24,0,0,0,0.40,3.0,500,2,0,0,0,...,0,0,0,1,4.0,1,1,1,1,1
25,0,4,0,2.20,5.0,550,2,0,0,0,...,0,0,0,0,2.0,1,1,1,0,0
26,0,4,0,0.00,5.0,550,0,1,0,0,...,0,0,0,1,4.0,1,1,1,1,0
27,0,0,0,0.30,5.0,500,0,0,0,1,...,0,0,0,0,2.0,1,1,1,1,0
28,0,4,0,0.00,5.0,700,2,0,0,0,...,0,0,0,0,3.0,1,1,1,1,1
29,0,11,1,0.00,5.0,550,1,1,0,0,...,0,0,0,0,4.0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,0,4,0,4.00,5.0,550,0,1,0,0,...,0,0,0,0,4.0,1,1,0,0,0
493,0,6,0,1.00,3.0,500,0,0,0,0,...,0,0,0,0,2.0,0,1,0,0,0
494,1,9,0,0.00,3.0,700,1,1,0,1,...,0,0,0,0,3.0,1,1,1,0,0
495,0,0,0,0.00,3.0,550,0,1,1,0,...,0,0,0,0,1.0,0,1,1,1,0
496,0,0,0,0.40,1.0,1000,0,0,0,1,...,0,0,0,0,1.0,0,1,1,1,0
497,0,0,0,1.00,5.0,500,0,1,0,0,...,0,0,0,0,4.0,1,1,0,0,0
498,0,1,0,1.08,1.0,500,1,1,1,0,...,0,0,0,0,2.0,1,1,0,0,1
499,0,17,0,1.00,1.0,500,0,0,0,0,...,0,0,0,0,1.0,1,0,0,0,0
500,0,51,0,0.00,3.0,550,1,1,0,0,...,0,0,0,0,2.0,1,1,0,0,0
501,0,9,0,6.00,1.0,500,1,1,1,0,...,0,0,0,0,4.0,0,1,0,0,0
502,0,5,0,0.30,10.0,500,0,0,0,0,...,0,0,0,0,2.0,0,1,1,0,0
503,0,16,0,1.00,3.0,550,0,0,0,0,...,0,0,0,0,2.0,0,1,1,0,0
504,0,18,0,0.00,5.0,550,0,0,0,0,...,1,0,0,1,4.0,0,1,0,0,0
505,1,81,0,0.00,3.0,400,0,1,0,0,...,0,0,1,0,3.0,0,1,1,0,1
506,0,18,0,0.00,3.0,550,0,0,0,0,...,0,0,0,0,2.0,1,1,0,0,0
507,0,0,0,0.00,3.0,550,0,0,1,0,...,0,0,0,1,2.0,0,1,0,0,0
508,1,0,0,3.00,3.0,500,0,0,0,0,...,0,0,0,0,4.0,1,1,0,0,0
509,0,23,0,3.00,1.0,550,0,0,0,0,...,0,0,0,1,2.0,0,1,0,0,0
510,0,82,0,4.00,3.0,500,0,0,0,0,...,0,0,0,0,2.0,1,1,1,1,1
511,0,83,0,2.00,3.0,500,0,0,0,1,...,0,0,0,1,2.0,1,1,1,1,1
512,0,5,0,0.00,10.0,450,1,1,0,0,...,0,0,0,0,2.0,1,1,0,0,1
513,0,3,1,5.00,3.0,500,0,0,0,0,...,0,0,0,1,2.0,1,1,1,1,1
514,0,51,0,0.00,3.0,550,1,1,1,0,...,0,0,0,0,2.0,1,1,0,0,0
515,0,84,0,1.00,3.0,500,1,1,1,0,...,0,0,0,0,2.0,1,1,0,0,0
516,0,34,0,0.00,5.0,700,0,1,0,2,...,0,0,0,0,4.0,1,1,1,0,0
517,0,0,0,3.00,10.0,550,0,0,0,1,...,0,0,0,1,4.0,1,1,1,1,1
518,0,27,1,3.00,3.0,500,0,1,0,0,...,0,0,0,0,2.0,1,1,1,1,1
519,0,23,0,4.00,10.0,500,2,1,2,0,...,0,0,0,0,2.0,0,1,1,0,0
520,0,11,0,2.00,5.0,500,1,1,1,0,...,0,0,0,0,3.0,1,1,0,0,0
521,1,51,0,0.00,3.0,550,0,0,0,0,...,0,0,0,0,1.0,1,1,0,0,1

In [55]:
budd_new.to_csv('budd_new_22_6_18.csv')

In [57]:
budd_new.columns

Index(['gender', 'current_city', 'open_to_other_branch', 'work_ex',
       'dist_from_uni', 'rent_budget', 'alcohol', 'smoking', 'food_pref',
       'cul_skills', 'looking_for_roommate', 'MS Biotechnology',
       'MS Civil Engineering', 'MS Computer Science',
       'MS Computer Systems Engineering', 'MS Data Science',
       'MS Electrical and Computer Engineering', 'MS Energy Systems',
       'MS Engineering Management', 'MS Industrial Engineering',
       'MS Information Assurance and Cyber Security', 'MS Information Systems',
       'MS Mechanical Engineering', 'MS Project Management', 'Others',
       'hall_yes_no', 'max_ppr', 'bhk_1', 'bhk_2', 'bhk_3', 'bhk_4', 'studio'],
      dtype='object')

In [67]:
budd_new.dtypes

gender                                           int64
current_city                                     int64
open_to_other_branch                             int64
work_ex                                        float64
dist_from_uni                                  float64
rent_budget                                     object
alcohol                                          int64
smoking                                          int64
food_pref                                        int64
cul_skills                                       int64
looking_for_roommate                             int64
MS Biotechnology                                 int64
MS Civil Engineering                             int64
MS Computer Science                              int64
MS Computer Systems Engineering                  int64
MS Data Science                                  int64
MS Electrical and Computer Engineering           int64
MS Energy Systems                                int64
MS Engineering Management                        int64
MS Industrial Engineering                        int64
MS Information Assurance and Cyber Security      int64
MS Information Systems                           int64
MS Mechanical Engineering                        int64
MS Project Management                            int64
Others                                           int64
hall_yes_no                                      int64
max_ppr                                        float64
bhk_1                                            int64
bhk_2                                            int64
bhk_3                                            int64
bhk_4                                            int64
studio                                           int64
dtype: object

In [63]:
pd.to_numeric(budd_new.rent_budget)

ValueError: Unable to parse string "$1000 +" at position 88

In [64]:
budd_new.rent_budget.value_counts()

500        165
550        134
700         84
450         79
400         34
1000        15
< $500       9
$1000 +      2
Name: rent_budget, dtype: int64

In [65]:
budd_new['rent_budget'].replace(['< $500','$1000 +'], [500, 1000], inplace = True)

In [69]:
budd_new.rent_budget.value_counts()

500     165
550     134
700      84
450      79
400      34
1000     15
500       9
1000      2
Name: rent_budget, dtype: int64

In [70]:
budd_new.rent_budget = pd.to_numeric(budd_new.rent_budget)

In [71]:
budd_new.rent_budget.value_counts()

500     174
550     134
700      84
450      79
400      34
1000     17
Name: rent_budget, dtype: int64

In [72]:
budd_new.dtypes

gender                                           int64
current_city                                     int64
open_to_other_branch                             int64
work_ex                                        float64
dist_from_uni                                  float64
rent_budget                                      int64
alcohol                                          int64
smoking                                          int64
food_pref                                        int64
cul_skills                                       int64
looking_for_roommate                             int64
MS Biotechnology                                 int64
MS Civil Engineering                             int64
MS Computer Science                              int64
MS Computer Systems Engineering                  int64
MS Data Science                                  int64
MS Electrical and Computer Engineering           int64
MS Energy Systems                                int64
MS Engineering Management                        int64
MS Industrial Engineering                        int64
MS Information Assurance and Cyber Security      int64
MS Information Systems                           int64
MS Mechanical Engineering                        int64
MS Project Management                            int64
Others                                           int64
hall_yes_no                                      int64
max_ppr                                        float64
bhk_1                                            int64
bhk_2                                            int64
bhk_3                                            int64
bhk_4                                            int64
studio                                           int64
dtype: object

In [73]:
budd_new.to_csv('budd_new_22_6_18.csv')